import * as THREE from './vendor/three.module.js';
const $=id=>document.getElementById(id),clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),distance=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z);
const NAMES=['Välj platta','Kurragömma','Monster','Akta pilarna','Where is Exit'];
const RULES=['Välj platta 1 eller 2 innan tiden är slut. En är rätt! Fel platta kostar ett liv.','En letar, resten gömmer sig. 20 sekunder att gömma sig, 15 att leta. Hittad = ett liv mindre.','Håll dig undan monstret i 10 sekunder. Om det tar dig förlorar du ett liv.','Överlev i 10 sekunder. Röda fält varnar för pilar. Ta dig till en grön lucka!','Hitta ut ur labyrinten först! De andra tappar ett liv. Monstret skickar dig till start.'];
const COLORS=[0x57dcce,0xf5b84f,0xa9a0ff,0xf68fa4,0x87c86b],BOT_NAMES=['Du','Milo','Nova','Rio','Lo'];
let renderer;try{renderer=new THREE.WebGLRenderer({canvas:$('game'),antialias:true,preserveDrawingBuffer:!!navigator.webdriver});}catch(e){$('error').hidden=false;throw e}
renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.5));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x7399a5);scene.fog=new THREE.Fog(0x7399a5,45,110);scene.add(new THREE.HemisphereLight(0xdff7ff,0x536357,2.5));scene.add(new THREE.AmbientLight(0xd9eeea,.65));const sun=new THREE.DirectionalLight(0xffedc9,2.4);sun.position.set(-15,30,12);scene.add(sun);
const camera=new THREE.PerspectiveCamera(72,1,.06,140);camera.rotation.order='YXZ';let world=new THREE.Group();scene.add(world);
const mats=new Map();function mat(c){if(!mats.has(c))mats.set(c,new THREE.MeshStandardMaterial({color:c,roughness:.8}));return mats.get(c)}
function box(w,h,d,x,y,z,c=0x42656b,parent=world){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat(c));m.position.set(x,y,z);parent.add(m);return m}
function sphere(r,x,y,z,c,parent=world){const m=new THREE.Mesh(new THREE.SphereGeometry(r,12,8),mat(c));m.position.set(x,y,z);parent.add(m);return m}
function label(text,x,y,z,width=4,color='#fff3cf'){const c=document.createElement('canvas');c.width=512;c.height=128;const g=c.getContext('2d');g.fillStyle='#102b35';g.roundRect(2,2,508,124,16);g.fill();g.fillStyle=color;g.textAlign='center';g.textBaseline='middle';g.font='bold 46px system-ui';g.fillText(text,256,64,485);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;const sprite=new THREE.Sprite(new THREE.SpriteMaterial({map:t,depthTest:true}));sprite.position.set(x,y,z);sprite.scale.set(width,width/4,1);sprite.userData.ownedTexture=true;world.add(sprite);return sprite}
let obstacles=[],spots=[],pads=[],doors=[],arrows=[],lanes=[],bounds={x:15,z:15},maze=null,monster=null,exit=null,nav=new Map();
const keys=new Set();let stick={x:0,y:0},look=null,stickPointer=null,last=performance.now(),manual=false;
const fresh=()=>({mode:'lobby',paused:false,practice:false,stage:0,cycle:1,phase:'intro',time:0,timer:0,actors:[],seeker:0,notice:'',noticeUntil:0,result:'',follow:0,correct:1,seed:Math.floor(Math.random()*1e9),volley:0,nextVolley:0,roundHits:[],stageElapsed:0});let s=fresh();
let rngState=1;function random(){rngState=(Math.imul(1664525,rngState)+1013904223)>>>0;return rngState/4294967296}function pick(a){return a[Math.floor(random()*a.length)]}
const alive=()=>s.actors.filter(a=>a.lives>0),player=()=>s.actors[0];
function createActor(id,lives){return{id,name:BOT_NAMES[id],lives,x:0,z:0,y:0,vy:0,yaw:0,pitch:0,hidden:-1,found:false,immune:0,choice:0,route:[],navAt:0,goal:null,speed:id===0?6:4.1+random()*.9,mesh:null}}
function character(a,lobby=false){const g=new THREE.Group();world.add(g);box(.66,.85,.4,0,1.06,0,COLORS[a.id],g);sphere(.28,0,1.72,0,0xffd3a0,g);box(.62,.16,.5,0,1.96,0,COLORS[a.id],g);box(.11,.1,.035,-.1,1.75,-.27,0x15313c,g);box(.11,.1,.035,.1,1.75,-.27,0x15313c,g);a.legs=[box(.2,.6,.23,-.19,.34,0,0x203b4c,g),box(.2,.6,.23,.19,.34,0,0x203b4c,g)];box(.18,.7,.2,-.45,1.03,0,COLORS[a.id],g);box(.18,.7,.2,.45,1.03,0,COLORS[a.id],g);a.mesh=g;a.tag=label(lobby?'BOT':a.name,0,2.4,0,1.8);return g}
function solid(x,z,w,d,h=3,color=0x54787d){box(w,h,d,x,h/2,z,color);obstacles.push({x,z,w,d});}
function clearWorld(){scene.remove(world);world.traverse(o=>{o.geometry?.dispose();if(o.userData.ownedTexture){o.material.map.dispose();o.material.dispose()}});world=new THREE.Group();scene.add(world);obstacles=[];spots=[];pads=[];doors=[];arrows=[];lanes=[];maze=null;monster=null;exit=null;nav.clear()}
function room(x,z,floor=0x698589,walls=0x31545f){bounds={x,z};box(x*2,.3,z*2,0,-.16,0,floor);solid(-x,0,.5,z*2,4,walls);solid(x,0,.5,z*2,4,walls);solid(0,-z,x*2,.5,4,walls);solid(0,z,x*2,.5,4,walls);for(let p=-x+2;p<x;p+=4){box(.06,.02,z*2,p,.01,0,0x8da1a0)}for(let p=-z+2;p<z;p+=4){box(x*2,.02,.06,0,.01,p,0x8da1a0)}}
function resetInput(){keys.clear();stick={x:0,y:0};look=null;stickPointer=null;$('knob').style.transform=''}
function lobby(){resetInput();s=fresh();rngState=s.seed;clearWorld();room(13,11,0x486c70,0x22424d);box(26,.2,22,0,5,0,0x183742);for(let i=0;i<3;i++){const x=(i-1)*8;box(4.2,4,.4,x,2,-9,0x152f39);box(3.4,3.5,.5,x,1.75,-8.8,[0x3d9a8c,0xb59f52,0xc57a59][i]);box(.13,3.6,.15,x-1.8,1.8,-8.4,0xffda7c);box(.13,3.6,.15,x+1.8,1.8,-8.4,0xffda7c);label(`${i+3} PERSONER`,x,4.25,-8.6,5);label(`${4-i} LIV VAR`,x,.6,-8.35,2.5);doors.push({x,z:-8,count:i+3});for(let j=0;j<i+2;j++){const a=createActor(j+1,4-i);a.x=x+(j-(i+1)/2)*1.25;a.z=-5.2;character(a,true);a.mesh.position.set(a.x,0,a.z);a.tag.position.set(a.x,2.4,a.z)}}camera.position.set(0,3.7,10);camera.lookAt(0,1.7,-6);$('lobby').hidden=false;$('overlay').hidden=true;$('pausePanel').hidden=true;sync()}
function buildPlates(){room(12,14);label('VÄLJ PLATTA',0,3.6,-12,7);for(let i=0;i<2;i++){const x=i===0?-4.8:4.8;const mesh=box(7,.16,7,x,.09,-5,i===0?0x368ca0:0xa48b57);pads.push({x,z:-5,w:7,d:7,mesh});label(String(i+1),x,2,-6,3.5)}for(let i=-1;i<=1;i++)box(.12,3,.12,i*8,1.5,-12,0xf0d18a)}
function addSpot(name,x,z,type){const id=spots.length;spots.push({id,name,x,z,type});const wood=0xa37c53,dark=0x406676;
if(type==='cabinet'){box(3,3,.2,x,1.5,z-1,wood);box(.2,3,2,x-1.4,1.5,z,wood);box(.2,3,2,x+1.4,1.5,z,wood);box(3,.2,2,x,3,z,wood);obstacles.push({x,z:z-1,w:3,d:.2});}
if(type==='table'||type==='sofa'){box(3.7,.25,2.3,x,1.6,z,type==='sofa'?0xb77477:wood);for(const dx of [-1.6,1.6])for(const dz of [-.8,.8])box(.2,1.6,.2,x+dx,.8,z+dz,dark);if(type==='sofa')box(3.7,1, .3,x,2,z+.95,0xa7676e)}
if(type==='tree'){solid(x,z-.7,.65,.65,4,wood);sphere(2.7,x,4.5,z-.7,0x4e8564);sphere(1.8,x-1,4,z-.3,0x6f9d66)}
if(type==='bush'){for(let j=0;j<5;j++)sphere(1.1,x+Math.sin(j*2)*.7,1,z+Math.cos(j*2)*.7,0x568367)}
if(type==='box'){box(3,.15,3,x,.08,z,wood);box(3,1.5,.15,x,.75,z-1.4,wood);box(.15,1.5,3,x-1.4,.75,z,wood);box(.15,1.5,3,x+1.4,.75,z,wood);box(3,.65,.15,x,.32,z+1.4,wood)}
if(type==='stairs'){for(let j=0;j<5;j++)solid(x+2,z+j*.7,2,.7,.5+j*.5,0x8d9c9b)}
if(type==='house'){solid(x,z-3,7,4,4,0xcdad81);box(7.5,.3,4.5,x,4.2,z-3,0x596c79);box(1.5,1.4,.05,x-1.8,2.5,z-.95,0x77bdc6)}
if(type==='hut'){solid(x-2,z,.25,5,2.8,wood);solid(x+2,z,.25,5,2.8,wood);box(4.4,.3,5.4,x,3,z,0x526d76);box(4.2,.1,.25,x,2.7,z-2.5,wood);box(4.2,.1,.25,x,2.7,z+2.5,wood)}
label(name,x,3.5,z,3.6);box(1.3,.035,1.3,x,.035,z,0x94c6a1)}
function buildHide(){room(24,23,0x6d8870,0x708986);addSpot('SKÅP',-17,-15,'cabinet');addSpot('BORD 1',-6,-14,'table');addSpot('BORD 2',7,-14,'table');addSpot('TRÄD',17,-12,'tree');addSpot('BAKOM HUSET',16,4,'house');addSpot('STOR LÅDA',-17,2,'box');addSpot('BUSKE',-5,5,'bush');addSpot('UNDER SOFFAN',5,6,'sofa');addSpot('BAKOM TRAPPAN',-16,16,'stairs');addSpot('KOJA · TVÅ ÖPPNINGAR',11,17,'hut');label('GÖM DIG!',0,4,-21,7)}
function makeMonster(x,z){const g=new THREE.Group();world.add(g);sphere(.85,0,1.35,0,0x493757,g);sphere(.42,0,1.65,-.65,0xfff8c1,g);sphere(.2,0,1.67,-1,0x151c2a,g);box(1.3,.3,.5,0,.6,-.5,0x977297,g);for(const dx of [-.7,.7]){box(.25,1.5,.28,dx,.8,0,0x4e3863,g);box(.32,.7,.25,dx,2.05,0,0x7f587e,g)}monster={x,z,mesh:g,route:[],navAt:0,speed:4.7};return monster}
function buildMonster(){room(17,17,0x657480,0x3f5365);for(const [x,z]of[[-7,-6],[7,-6],[-7,6],[7,6]]){solid(x,z,3,3,3.3,0x567d85);box(3.1,.15,3.1,x,3.4,z,0xe3c373)}label('HÅLL DIG UNDAN',0,4,-15,8);makeMonster(0,-11)}
function buildArrows(){room(12,16,0x667b81,0x3d5967);for(let i=0;i<7;i++){const x=(i-3)*3;box(.9,.9,.6,x,1,-15,0x182c3b);label('▼',x,2.5,-14.8,1.4);lanes.push({x,safe:false,pad:box(2.85,.04,29,x,.03,0,0x637c80),light:box(.9,.12,.7,x,1.8,-14.8,0xef9f71)})}label('AKTA PILARNA',0,4,-15,8)}
function buildMaze(){const cols=6,rows=5,cell=5,ox=-cols*cell/2,oz=-rows*cell/2;room(cols*cell/2+1,rows*cell/2+1,0x758287,0x405865);const cells=Array.from({length:cols*rows},(_,i)=>({i,walls:[true,true,true,true],seen:false}));const stack=[0];cells[0].seen=true;const dirs=[[0,-1],[1,0],[0,1],[-1,0]];while(stack.length){const cur=stack.at(-1),x=cur%cols,z=Math.floor(cur/cols),options=[];dirs.forEach(([dx,dz],d)=>{const nx=x+dx,nz=z+dz;if(nx>=0&&nz>=0&&nx<cols&&nz<rows&&!cells[nz*cols+nx].seen)options.push([nz*cols+nx,d])});if(!options.length){stack.pop();continue}const [next,d]=pick(options);cells[cur].walls[d]=false;cells[next].walls[(d+2)%4]=false;cells[next].seen=true;stack.push(next)}
const center=i=>({x:ox+(i%cols+.5)*cell,z:oz+(Math.floor(i/cols)+.5)*cell});for(const c of cells){const p=center(c.i);if(c.walls[0])solid(p.x,p.z-cell/2,cell,.35,3.2,0x668089);if(c.walls[3])solid(p.x-cell/2,p.z,.35,cell,3.2,0x668089);if(c.i%cols===cols-1)solid(p.x+cell/2,p.z,.35,cell,3.2,0x668089);if(c.i>=cols*(rows-1))solid(p.x,p.z+cell/2,cell,.35,3.2,0x668089)}const ds=new Map([[0,0]]),queue=[0];while(queue.length){const n=queue.shift();cells[n].walls.forEach((wall,d)=>{if(!wall){const j=n+dirs[d][0]+dirs[d][1]*cols;if(!ds.has(j)){ds.set(j,ds.get(n)+1);queue.push(j)}}})}const far=[...ds].sort((a,b)=>b[1]-a[1])[0][0];exit={...center(far),cell:far};maze={cols,rows,cell,ox,oz,cells,start:center(0),end:far,dist:ds.get(far)};box(3,.08,3,maze.start.x,.06,maze.start.z,0x51c8c7);label('START',maze.start.x,2.8,maze.start.z,3);box(3,.08,3,exit.x,.06,exit.z,0x71ca80);label('EXIT',exit.x,2.7,exit.z,3.5,'#a5ffc2');const mp=center(Math.floor(cols*rows/2));makeMonster(mp.x,mp.z);monster.speed=4.1}
function blocked(x,z,r=.36){return Math.abs(x)>bounds.x-.65||Math.abs(z)>bounds.z-.65||obstacles.some(o=>Math.abs(x-o.x)<o.w/2+r&&Math.abs(z-o.z)<o.d/2+r)}
function move(a,dx,dz){if(!blocked(a.x+dx,a.z))a.x+=dx;if(!blocked(a.x,a.z+dz))a.z+=dz}
function lineClear(a,b){const n=Math.ceil(distance(a,b)*3);for(let i=1;i<n;i++)if(blocked(a.x+(b.x-a.x)*i/n,a.z+(b.z-a.z)*i/n,.4))return false;return true}
function pathTo(a,target){const step=1,key=(x,z)=>`${x},${z}`,sx=Math.round(a.x),sz=Math.round(a.z),tx=Math.round(target.x),tz=Math.round(target.z),open=[[sx,sz]],from=new Map([[key(sx,sz),null]]);let found=null;for(let i=0;i<open.length&&i<6000;i++){const [x,z]=open[i];if(Math.hypot(x-tx,z-tz)<1.2){found=[x,z];break}for(const [dx,dz]of[[1,0],[-1,0],[0,1],[0,-1]]){const nx=x+dx*step,nz=z+dz*step,k=key(nx,nz);if(!from.has(k)&&!blocked(nx,nz,.4)){from.set(k,[x,z]);open.push([nx,nz])}}}if(!found)return[];const path=[];while(found){path.push({x:found[0],z:found[1]});found=from.get(key(...found))}return path.reverse().slice(1).concat([{x:target.x,z:target.z}])}
function travel(a,target,dt,speed=a.speed){if(!target)return;let goal=target;if(lineClear(a,target)){a.route=[];}else{if(s.time>a.navAt||!a.route?.length){a.route=pathTo(a,target);a.navAt=s.time+.85}while(a.route.length&&distance(a,a.route[0])<.25)a.route.shift();goal=a.route[0];}if(!goal)return;const d=distance(a,goal);if(d>.05){const amount=Math.min(d,speed*dt),dx=(goal.x-a.x)/d*amount,dz=(goal.z-a.z)/d*amount;move(a,dx,dz);a.yaw=Math.atan2(-dx,-dz)}}
function spawnActors(){const living=alive();living.forEach((a,i)=>{a.hidden=-1;a.found=false;a.choice=0;a.immune=1.5;a.y=0;a.vy=0;a.yaw=0;a.pitch=0;a.route=[];a.navAt=0;a.goal=null;a.x=(i-(living.length-1)/2)*1.4;a.z=s.stage===1?19:s.stage===2?11:10;if(s.stage===4){a.x=maze.start.x+(i%3-1)*.65;a.z=maze.start.z+Math.floor(i/3)*.7;const d=maze.cells[0].walls.findIndex(w=>!w);a.yaw=d===1?-Math.PI/2:Math.PI}character(a)});s.actors.filter(a=>a.lives<=0).forEach(a=>{a.mesh=null;a.tag=null});if(!player().lives)s.follow=alive()[0]?.id||0}
function setStage(n){resetInput();s.stage=n;s.stageElapsed=0;s.phase=s.practice?'active':'intro';s.timer=s.practice?0:4;s.roundHits=[];s.volley=0;s.nextVolley=0;s.arrowPhase=null;s.safeLanes=[];clearWorld();[buildPlates,buildHide,buildMonster,buildArrows,buildMaze][n]();spawnActors();if(n===0){s.correct=random()<.5?1:2;for(const a of alive().filter(a=>a.id)){a.choice=random()<.5?1:2;a.goal=pads[a.choice-1]}}
if(n===1){s.seeker=pick(alive()).id;const hiding=alive().filter(a=>a.id!==s.seeker);const available=[...spots];for(const a of hiding.filter(a=>a.id)){a.hideTarget=available.splice(Math.floor(random()*available.length),1)[0].id}const seeker=s.actors[s.seeker];seeker.x=0;seeker.z=0;seeker.searchOrder=[...spots].sort(()=>random()-.5).map(x=>x.id);seeker.searchIndex=0}
if(s.practice){s.phase='practice';$('overlay').hidden=true}else{$('overlayLabel').textContent=`BANA ${n+1} / 5 · VARV ${s.cycle}`;$('overlayTitle').textContent=NAMES[n];$('overlayText').textContent=RULES[n]+(n===1?`\n${BOT_NAMES[s.seeker]} letar.`:'');$('continue').textContent='Kör!';$('overlay').hidden=false}sync()}
function start(count,practice=false){s=fresh();s.mode='playing';s.practice=practice;rngState=s.seed;s.actors=Array.from({length:count},(_,id)=>createActor(id,7-count));$('lobby').hidden=true;$('pausePanel').hidden=true;setStage(0);$('game').focus()}
function beginStage(){if(s.mode!=='playing'||s.phase!=='intro')return;s.phase=s.stage===1?'hide':'active';s.timer=[8,20,10,10,0][s.stage];s.stageElapsed=0;$('overlay').hidden=true;sync()}
function say(text){s.notice=text;s.noticeUntil=s.time+3}
function damage(a,reason){if(s.practice||a.lives<=0)return;a.lives--;a.immune=2;s.roundHits.push(`${a.name}: ${reason}`);say(`${a.name}: −1 liv${a.lives===0?' · åkte ut':''}`);if(a.lives===0){a.eliminatedAt=s.time;a.hidden=-1;if(s.follow===a.id)s.follow=alive()[0]?.id||0;if(a.id===0){s.follow=alive()[0]?.id||0;say('Du är ute. Titta på resten av matchen!')}if(a.mesh)a.mesh.visible=false;if(a.tag)a.tag.visible=false}sync()}
function checkWinner(){if(s.practice)return false;const remain=alive();if(remain.length===1){s.mode='won';s.phase='won';s.result=`${remain[0].name==='Du'?'Du vann!':remain[0].name+' vann!'}`;$('overlayLabel').textContent='SIST KVAR';$('overlayTitle').textContent=s.result;$('overlayText').textContent='Fem banor. En vinnare. Vill du spela igen?';$('continue').textContent='Till korridoren';$('overlay').hidden=false;resetInput();sync();return true}if(remain.length===0){const latest=Math.max(...s.actors.map(a=>a.eliminatedAt??-1));for(const a of s.actors.filter(a=>a.eliminatedAt===latest)){a.lives=1;a.immune=3;a.found=false;a.hidden=-1}say('Lika! De sista får ett liv och spelar vidare.');s.follow=alive()[0]?.id||0;sync();return false}return false}
function finish(text){if(s.phase==='result'||s.mode!=='playing')return;if(checkWinner())return;s.phase='result';s.timer=3;s.result=text;say(text);sync()}
function next(){if(s.stage===4)s.cycle++;setStage((s.stage+1)%5)}
function closestSpot(a){return spots.filter(p=>distance(a,p)<2.5).sort((a1,b)=>distance(a,a1)-distance(a,b))[0]}
function use(){if(s.mode!=='playing'||s.paused)return;if(s.phase==='intro'){beginStage();return}const a=player();if(a.lives<=0){followNext();return}if(s.stage===1){if(a.hidden>=0){a.hidden=-1;say('Du lämnade gömstället.');return}const p=closestSpot(a);if(!p){say('Gå närmare ett gömställe.');return}if(s.practice||s.seeker!==0){a.hidden=p.id;a.x=p.x;a.z=p.z;say(`Gömmer dig: ${p.name.toLowerCase()}`)}else if(s.phase==='seek'){searchSpot(a,p);say(`Du sökte i ${p.name.toLowerCase()}.`)}}
if(s.stage===0&&!s.practice){const idx=pads.findIndex(p=>Math.abs(a.x-p.x)<p.w/2&&Math.abs(a.z-p.z)<p.d/2);if(idx>=0){a.choice=idx+1;say(`Du valde platta ${a.choice}.`)}}}
function searchSpot(seeker,p){for(const a of alive()){if(a.id!==seeker.id&&!a.found&&a.hidden===p.id){a.found=true;a.hidden=-1;damage(a,'hittad');}}}
function followNext(){const list=alive();const i=list.findIndex(a=>a.id===s.follow);s.follow=list[(i+1)%list.length]?.id||0;sync()}
function fireVolley(){const safe=Math.floor(random()*7);s.safeLanes=[safe,(safe+1)%7];s.volley++;s.arrowPhase='warning';s.nextVolley=s.stageElapsed+1.1;for(let i=0;i<7;i++){lanes[i].safe=s.safeLanes.includes(i);lanes[i].pad.material=mat(lanes[i].safe?0x4baf8e:0xa55857);lanes[i].light.material=mat(lanes[i].safe?0x7df6b8:0xffa67d)}}
function releaseArrows(){s.arrowPhase='flying';s.nextVolley=s.stageElapsed+1.7;for(const lane of lanes.filter(l=>!l.safe)){for(const off of [-.75,0,.75]){const mesh=new THREE.Group();world.add(mesh);box(.07,.07,1.1,0,1,0,0xe9dbc0,mesh);const head=new THREE.Mesh(new THREE.ConeGeometry(.18,.45,4),mat(0xffd378));head.rotation.x=Math.PI/2;head.position.set(0,1,.65);mesh.add(head);arrows.push({x:lane.x+off,z:-14,mesh})}}}
function playerMovement(dt){const a=player();if(!a||a.lives<=0||a.hidden>=0)return;if(s.stage===1&&s.seeker===0&&s.phase==='hide')return;let dx=stick.x+(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0),dz=stick.y+(keys.has('KeyS')||keys.has('ArrowDown')?1:0)-(keys.has('KeyW')||keys.has('ArrowUp')?1:0);const len=Math.hypot(dx,dz);if(len>1){dx/=len;dz/=len}move(a,(Math.cos(a.yaw)*dx+Math.sin(a.yaw)*dz)*dt*a.speed,(-Math.sin(a.yaw)*dx+Math.cos(a.yaw)*dz)*dt*a.speed);a.vy-=16*dt;a.y=Math.max(0,a.y+a.vy*dt);if(!a.y)a.vy=0}
function jump(){const a=player();if(a&&s.mode==='playing'&&!s.paused&&a.lives>0&&a.y===0&&a.hidden<0)a.vy=5.4}
function botUpdate(a,dt){if(a.found||a.hidden>=0)return;if(s.stage===0)travel(a,a.goal,dt);if(s.stage===1){if(a.id===s.seeker){if(s.phase==='hide')return;const target=spots[a.searchOrder[a.searchIndex%spots.length]];travel(a,target,dt,7);if(distance(a,target)<2){searchSpot(a,target);a.searchIndex++;a.navAt=0}for(const h of alive().filter(h=>h.id!==a.id&&h.hidden<0&&!h.found)){if(distance(a,h)<2.1&&lineClear(a,h)){h.found=true;damage(h,'hittad')}}}else{const target=spots[a.hideTarget];travel(a,target,dt);if(distance(a,target)<.65){a.hidden=target.id;a.x=target.x;a.z=target.z}}}
if(s.stage===2){if(!a.goal||distance(a,a.goal)<1||s.time>a.goalTime){const candidates=Array.from({length:12},()=>({x:(random()-.5)*28,z:(random()-.5)*28})).filter(p=>!blocked(p.x,p.z));candidates.sort((p,q)=>(distance(q,monster)-distance(a,q)*.25)-(distance(p,monster)-distance(a,p)*.25));a.goal=candidates[0];a.goalTime=s.time+1.5}travel(a,a.goal,dt)}
if(s.stage===3&&s.safeLanes?.length){if(a.volley!==s.volley){a.volley=s.volley;a.reaction=s.time+.22+random()*.55;a.dodge=pick(s.safeLanes);a.goal={x:lanes[a.dodge].x,z:5+(a.id%3)*2}}if(s.time>a.reaction)travel(a,a.goal,dt,a.speed*1.25)}
if(s.stage===4)travel(a,exit,dt)}
function monsterUpdate(dt){if(s.time<(monster.sleepUntil||0))return;const candidates=alive().filter(a=>a.immune<=0);if(!candidates.length)return;const target=candidates.sort((a,b)=>distance(a,monster)-distance(b,monster))[0];travel(monster,target,dt,monster.speed);for(const a of alive()){if(a.immune<=0&&distance(a,monster)<1.1){if(s.stage===4){a.x=maze.start.x;a.z=maze.start.z;a.route=[];a.navAt=0;a.immune=3;monster.x=maze.start.x;monster.z=maze.start.z;monster.route=[];monster.navAt=0;monster.sleepUntil=s.time+2.5;say(`${a.name} tillbaka till start!`)}else{damage(a,'tagen av monstret');a.x=(a.id-2)*1.5;a.z=12;a.goal=null}}}}
function step(dt){if(s.paused||s.mode!=='playing')return;s.time+=dt;if(s.phase==='intro'){s.timer-=dt;if(s.timer<=0)beginStage();return}if(s.phase==='result'){s.timer-=dt;if(s.timer<=0)next();return}playerMovement(dt);for(const a of s.actors)a.immune=Math.max(0,a.immune-dt);if(s.practice)return;if(s.stage!==4)s.timer-=dt;s.stageElapsed+=dt;for(const a of alive().filter(a=>a.id))botUpdate(a,dt);
if(s.stage===0){const a=player();if(a.lives>0){const p=pads.findIndex(p=>Math.abs(a.x-p.x)<p.w/2&&Math.abs(a.z-p.z)<p.d/2);a.choice=p+1}if(s.timer<=0){const incorrect=alive().filter(a=>a.choice!==s.correct);for(const a of incorrect)damage(a,'fel platta');pads.forEach((p,i)=>p.mesh.material=mat(i+1===s.correct?0x66dfab:0xc46464));finish(`Platta ${s.correct} var rätt!`);}}
if(s.stage===1){if(s.phase==='hide'&&s.timer<=0){s.phase='seek';s.timer=15;say(`${BOT_NAMES[s.seeker]} börjar leta!`)}else if(s.phase==='seek'){if(s.seeker===0&&player().lives>0){for(const a of alive().filter(a=>a.id!==0&&a.hidden<0&&!a.found)){if(distance(a,player())<2.1&&lineClear(a,player())){a.found=true;damage(a,'hittad')}}}if(s.timer<=0)finish('Kurragömman är klar!')}}
if(s.stage===2){monsterUpdate(dt);if(s.timer<=0)finish('Tio sekunder avklarade!')}
if(s.stage===3){if(s.stageElapsed>=s.nextVolley){if(s.arrowPhase==='warning')releaseArrows();else fireVolley()}for(const arrow of [...arrows]){arrow.z+=23*dt;arrow.mesh.position.set(arrow.x,0,arrow.z);for(const a of alive()){if(a.immune<=0&&Math.abs(a.x-arrow.x)<.53&&Math.abs(a.z-arrow.z)<.8&&a.y<.9){damage(a,'träffad av en pil')}}if(arrow.z>15){world.remove(arrow.mesh);arrow.mesh.traverse(o=>o.geometry?.dispose());arrows.splice(arrows.indexOf(arrow),1)}}if(s.timer<=0)finish('Du klarade pilväggen!')}
if(s.stage===4){monsterUpdate(dt);const finishers=alive().filter(a=>distance(a,exit)<1.2);if(finishers.length){const winner=finishers.sort((a,b)=>distance(a,exit)-distance(b,exit))[0];for(const a of alive().filter(a=>a.id!==winner.id))damage(a,'hann inte först till EXIT');finish(`${winner.name} nådde EXIT först!`)}}if(s.mode==='playing'&&s.phase!=='result')checkWinner();}
function updateVisuals(){for(const a of s.actors){if(!a.mesh)continue;a.mesh.position.set(a.x,a.y,a.z);a.mesh.rotation.y=a.yaw;a.mesh.visible=a.lives>0&&a.id!==0&&a.hidden<0&&(player().lives<=0||distance(a,player())>1.7);a.tag.visible=a.mesh.visible;a.tag.position.set(a.x,2.45+a.y,a.z);a.legs?.forEach((leg,i)=>leg.rotation.x=Math.sin(s.time*8+i*Math.PI)*.25)}if(monster){monster.mesh.position.set(monster.x,0,monster.z);monster.mesh.rotation.y=monster.yaw||0}if(s.mode!=='lobby'){const a=player().lives>0?player():s.actors[s.follow]||alive()[0];if(a){const spectating=player().lives<=0;if(spectating){const behind={x:a.x+Math.sin(a.yaw)*4,z:a.z+Math.cos(a.yaw)*4};const clear=lineClear(a,behind);camera.position.set(clear?behind.x:a.x,clear?3.8:2.6,clear?behind.z:a.z);camera.lookAt(a.x-Math.sin(a.yaw)*3,1.5,a.z-Math.cos(a.yaw)*3)}else{camera.position.set(a.x,a.y+(a.hidden>=0?.85:1.7),a.z);camera.rotation.set(a.pitch,a.yaw,0)}}}}
function sync(){const lobbyMode=s.mode==='lobby',playing=s.mode==='playing',p=player();$('lobby').hidden=!lobbyMode;$('touch').hidden=!playing||s.paused||!p?.lives||s.phase==='intro';$('crosshair').hidden=lobbyMode||s.paused;$('spectate').hidden=!playing||!!p?.lives||s.paused;$('round').textContent=lobbyMode?'AGUST GAMES':s.practice?'PRACTICE · UTFORSKA I LUGN OCH RO':`VARV ${s.cycle} · BANA ${s.stage+1} / 5`;$('title').innerHTML=lobbyMode?'WHERE’S EXIT <em>MULTI</em>':NAMES[s.stage];$('timer').textContent=playing&&!s.practice&&s.phase!=='intro'?(s.stage===4?'EXIT':Math.max(0,Math.ceil(s.timer))+''):'';$('objective').textContent=lobbyMode?'Välj en dörr för att börja.':s.practice?'Inga liv försvinner. Välj nästa bana när du vill.':p?.lives<=0?`Åskådare · följer ${BOT_NAMES[s.follow]}`:s.phase==='intro'?RULES[s.stage]:s.stage===1?(s.phase==='hide'?s.seeker===0?'Du letar. Vänta medan de andra gömmer sig.':'Göm dig! Gå nära ett gömställe och tryck GÖM DIG.':s.seeker===0?'Leta! Gå till gömställen och tryck SÖK.':`${BOT_NAMES[s.seeker]} letar. Stanna gömd!`):RULES[s.stage];$('roster').innerHTML=s.actors.map(a=>`<span class="person ${a.lives?'':'out'}" style="--color:#${COLORS[a.id].toString(16)}"><b>${a.name}</b><span class="hearts">${a.lives?'♥'.repeat(a.lives):'UTE'}</span></span>`).join('');$('notice').textContent=s.time<s.noticeUntil?s.notice:'';let prompt='';if(playing&&p?.lives>0&&s.stage===1&&s.phase!=='intro'){const spot=closestSpot(p);if(p.hidden>=0)prompt='Du är gömd · E / LÄMNA för att gå ut';else if(spot)prompt=`${spot.name} · E / ${s.seeker===0&&!s.practice?'SÖK':'GÖM DIG'}`}$('prompt').textContent=prompt;$('use').textContent=s.stage===1?(p?.hidden>=0?'LÄMNA':s.seeker===0&&!s.practice?'SÖK':'GÖM DIG'):'ANVÄND';$('practiceNav').hidden=!s.practice||s.paused;$('seekerCurtain').hidden=!(playing&&!s.practice&&s.stage===1&&s.seeker===0&&s.phase==='hide');}
function render(){updateVisuals();sync();renderer.render(scene,camera)}
function resize(){renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()}window.addEventListener('resize',resize);resize();
function pause(value=!s.paused){if(s.mode!=='playing')return;s.paused=value;resetInput();$('pausePanel').hidden=!value;sync()}
$('pause').onclick=()=>pause();$('resume').onclick=()=>pause(false);$('restart').onclick=lobby;$('continue').onclick=()=>s.mode==='won'||s.mode==='draw'?lobby():beginStage();document.querySelectorAll('[data-count]').forEach(b=>b.onclick=()=>start(+b.dataset.count));$('use').onclick=use;$('jump').onpointerdown=e=>{e.preventDefault();jump()};$('spectate').onclick=followNext;
async function fullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{say('Helskärm stöds inte här. Du kan spela ändå.')}}$('fullscreen').onclick=fullscreen;
window.addEventListener('keydown',e=>{if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();keys.add(e.code);if(e.repeat)return;if(e.code==='KeyE')use();if(e.code==='Space')jump();if(e.code==='Escape')pause();if(e.code==='KeyF')fullscreen()});window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>{if(s.mode==='playing')pause(true)});document.addEventListener('visibilitychange',()=>{if(document.hidden&&s.mode==='playing')pause(true)});
$('game').addEventListener('pointerdown',e=>{if(s.mode==='playing'&&!s.paused){look={id:e.pointerId,x:e.clientX,y:e.clientY};$('game').setPointerCapture(e.pointerId)}});$('game').addEventListener('pointermove',e=>{if(look?.id===e.pointerId&&player()){player().yaw-=(e.clientX-look.x)*.005;player().pitch=clamp(player().pitch-(e.clientY-look.y)*.004,-1.2,1.2);look.x=e.clientX;look.y=e.clientY}});for(const type of ['pointerup','pointercancel'])$('game').addEventListener(type,()=>look=null);
function stickMove(e){const r=$('stick').getBoundingClientRect(),radius=r.width*.34,x=clamp((e.clientX-r.x-r.width/2)/radius,-1,1),y=clamp((e.clientY-r.y-r.height/2)/radius,-1,1);const len=Math.max(1,Math.hypot(x,y));stick={x:x/len,y:y/len};$('knob').style.transform=`translate(${stick.x*radius}px,${stick.y*radius}px)`}
$('stick').addEventListener('pointerdown',e=>{stickPointer=e.pointerId;$('stick').setPointerCapture(e.pointerId);stickMove(e)});$('stick').addEventListener('pointermove',e=>{if(e.pointerId===stickPointer)stickMove(e)});for(const type of ['pointerup','pointercancel'])$('stick').addEventListener(type,()=>{stickPointer=null;stick={x:0,y:0};$('knob').style.transform=''})
const practiceButton=document.createElement('button');practiceButton.id='practice';practiceButton.textContent='PRACTICE · Se alla banor';practiceButton.onclick=()=>start(3,true);$('lobby').insertBefore(practiceButton,$('lobby').querySelector('.controls-help'));const practiceNav=document.createElement('div');practiceNav.id='practiceNav';practiceNav.hidden=true;practiceNav.style.cssText='position:absolute;left:50%;bottom:24px;transform:translateX(-50%);display:flex;gap:8px;z-index:3';for(const [text,delta]of[['← Bana',-1],['Nästa bana →',1]]){const b=document.createElement('button');b.textContent=text;b.onclick=()=>setStage((s.stage+delta+5)%5);practiceNav.append(b)}document.body.append(practiceNav);
window.render_game_to_text=()=>JSON.stringify({version:'20261009-multi-2',coordinates:'x right/east, z toward camera/south; y height; world units',mode:s.mode,paused:s.paused,practice:s.practice,stage:s.stage+1,stageName:NAMES[s.stage],cycle:s.cycle,phase:s.phase,timer:+s.timer.toFixed(2),seeker:s.stage===1?BOT_NAMES[s.seeker]:null,player:pState(player()),actors:s.actors.map(pState),follow:s.follow,monster:monster?{x:monster.x,z:monster.z}:null,spots:spots.map(({id,name,x,z})=>({id,name,x,z})),plates:pads.map(({x,z},i)=>({number:i+1,x,z})),safeLanes:s.safeLanes||[],arrows:arrows.map(a=>({x:a.x,z:a.z})),maze:maze?{start:maze.start,exit,steps:maze.dist,layout:maze.cells.map(c=>c.walls.map(Number).join('')).join('-')}:null,result:s.result,notice:s.time<s.noticeUntil?s.notice:'',doors:doors.map(d=>({count:d.count,lives:7-d.count,bots:d.count-1}))});
function pState(a){return a?{id:a.id,name:a.name,lives:a.lives,x:+a.x.toFixed(2),z:+a.z.toFixed(2),y:+a.y.toFixed(2),yaw:a.yaw,hidden:a.hidden,found:a.found,choice:a.choice,immune:a.immune}:null}
window.advanceTime=ms=>{manual=true;for(let left=ms;left>0;left-=1000/60)step(Math.min(left/1000,1/60));render()};if(['localhost','127.0.0.1'].includes(location.hostname)||new URLSearchParams(location.search).has('qa'))window.__multi={get state(){return s},get world(){return{obstacles,spots,pads,monster,maze,exit,lanes,bounds}},start,setStage,beginStage,damage,checkWinner,finish,step,pathTo,travel,use,render,lobby,place(x,z){Object.assign(player(),{x,z,hidden:-1,y:0,vy:0})},setSeed(seed){rngState=seed},freeze(){manual=true}};
function frame(now){if(!manual)step(Math.min((now-last)/1000,.05));last=now;render();requestAnimationFrame(frame)}lobby();requestAnimationFrame(frame);
