import {homedir} from 'node:os';import fs from 'node:fs/promises';
const {chromium,webkit}=await import(`${homedir()}/.codex/skills/develop-web-game/node_modules/playwright/index.mjs`);
const base=process.env.GAME_URL||'http://127.0.0.1:8133/where-is-exit-3/?qa=1',out=process.env.QA_OUT||'output/geography-spider';await fs.mkdir(out,{recursive:true});
const browser=await(process.env.ENGINE==='webkit'?webkit:chromium).launch({headless:true,args:process.env.ENGINE==='webkit'?[]:['--use-gl=angle','--use-angle=swiftshader']});const page=await browser.newPage({viewport:{width:1180,height:820},hasTouch:true}),checks=[],errors=[];page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
const check=(name,pass,details)=>{checks.push({name,pass:!!pass,details});console.log((pass?'PASS ':'FAIL ')+name+(!pass?' '+JSON.stringify(details||''):''))};
await page.goto(base,{waitUntil:'networkidle'});await page.waitForFunction(()=>!!window.__exit3);await page.locator('#start').tap();
async function chase(from,to,seconds){return page.evaluate(({from,to,seconds})=>{const a=window.__exit3;a.state.immuneUntil=1e7;a.state.gym.phase='balls';Object.assign(a.state.monsters.spider,from,{navigation:null,slowUntil:0});a.place(to.x,to.z);let collision=false;const trace=[];for(let i=0;i<seconds*60;i++){const m=a.state.monsters.spider,before={x:m.x,z:m.z};a.update(1/60);if(a.gymNavigator.blocked(m.x,m.z)||!a.gymNavigator.clear(before,m))collision=true;if(i%60===0)trace.push({x:m.x,z:m.z});if(Math.hypot(m.x-to.x,m.z-to.z)<1.3)break}const m=a.state.monsters.spider;return {close:Math.hypot(m.x-to.x,m.z-to.z)<1.7,collision,trace,end:{x:m.x,z:m.z}}},{from,to,seconds})}
const q=await page.evaluate(()=>window.__exit3.constants.GYM.hideouts[0]);let r=await chase({x:q.x,z:q.z-2},{x:q.x,z:q.z+13},30);check('Verkligt U-gömställe rundas utåt',r.close&&!r.collision,r.end);r=await chase({x:q.x,z:q.z+13},{x:q.x,z:q.z-2},30);check('Verkligt U-gömställe rundas inåt',r.close&&!r.collision,r.end);
await page.evaluate(()=>{const a=window.__exit3;a.state.gym.phase='balls';a.state.immuneUntil=1e7;Object.assign(a.state.monsters.spider,{x:125,z:-60,navigation:null,slowUntil:0});a.place(166,-60);window.advanceTime(1000)});
const built=await page.evaluate(()=>{const a=window.__exit3,before=a.world.pieces.length;for(let i=0;i<14;i++){const z=-76.8+i*2.4;a.place(141.6,z+4);a.buildAction('cube');a.buildAction('place')}a.place(166,-60);return a.world.pieces.length-before});check('Dynamisk vägg byggs med spelets riktiga byggfunktion',built===14,built);
const nav=await page.evaluate(()=>{const a=window.__exit3;let collided=false;for(let i=0;i<1620;i++){const m=a.state.monsters.spider,p={x:m.x,z:m.z};a.update(1/60);if(!a.gymNavigator.clear(p,m))collided=true}const m=a.state.monsters.spider;return {x:m.x,z:m.z,replans:m.navigation.replans,collided}});check('Åttaben räknar om vägen och rundar nybyggda kuber',Math.hypot(nav.x-166,nav.z+60)<1.7&&nav.replans>=2&&!nav.collided,nav);
const removed=await page.evaluate(()=>{const a=window.__exit3,before=a.world.pieces.length;for(const z of [-62.4,-60,-57.6]){a.place(137.6,z,0,-Math.PI/2);a.buildAction('pickup')}return before-a.world.pieces.length});check('Byggdelar kan flyttas för att öppna väg igen',removed===3,removed);
r=await chase({x:155,z:-60},{x:126,z:-60},20);check('Åttaben tar sig tillbaka genom ändrat bygge',r.close&&!r.collision,r.end);
await page.evaluate(q=>{const a=window.__exit3;a.state.gym.phase='seek';a.state.gym.timer=30;a.state.gym.spotted=0;a.state.immuneUntil=0;Object.assign(a.state.monsters.spider,{x:q.x,z:q.z+13,target:0,navigation:null});a.place(q.x,q.z-2);a.state.testCatches=a.state.catches;window.advanceTime(10000)},q);const s=await page.evaluate(()=>JSON.parse(window.render_game_to_text()));check('Gömstället döljer fortfarande spelaren under letandet',s.gym.phase==='seek'&&s.gym.timer<21);await page.screenshot({path:out+'/hidden-from-spider.png'});
check('Inga webbläsarfel',errors.length===0,errors);await fs.writeFile(out+'/report.json',JSON.stringify({checks,errors,base},null,2));await browser.close();console.log(`RESULT ${checks.filter(c=>c.pass).length}/${checks.length}`);if(checks.some(c=>!c.pass))process.exitCode=1;
