import { homedir } from 'node:os';
const {chromium,webkit}=await import(process.env.PLAYWRIGHT_MODULE||`${homedir()}/.codex/skills/develop-web-game/node_modules/playwright/index.mjs`);
import fs from 'node:fs/promises';
const out=process.env.QA_OUT||'output/exit3-edges',base=process.env.GAME_URL||'http://127.0.0.1:8133/where-is-exit-3/?qa=1';await fs.mkdir(out,{recursive:true});
const browser=await(process.env.ENGINE==='webkit'?webkit:chromium).launch({headless:true,args:process.env.ENGINE==='webkit'?[]:['--use-gl=angle','--use-angle=swiftshader']});
const page=await browser.newPage({viewport:{width:1180,height:820},isMobile:true,hasTouch:true});const checks=[],errors=[];page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
const state=()=>page.evaluate(()=>JSON.parse(window.render_game_to_text())),step=ms=>page.evaluate(ms=>window.advanceTime(ms),ms),place=(x,z,y=0,yaw=0)=>page.evaluate(a=>window.__exit3.place(...a),[x,z,y,yaw]);
const press=async(k,ms=0)=>{await page.keyboard.down(k);if(ms)await step(ms);await page.keyboard.up(k)};
const check=(name,ok,detail)=>{checks.push({name,pass:!!ok,detail});console.log((ok?'PASS ':'FAIL ')+name+(ok?'':' '+JSON.stringify(detail)))};
await page.goto(base,{waitUntil:'networkidle'});await page.locator('#start').tap();await step(20);
// Every room is reachable through its actual corridor opening.
for(const [id,x,z] of [['math',-15,36],['swedish',-15,10],['english',-15,-16],['social',15,36],['science',15,10],['gym',15,-21]]){await place(x<0?-1:1,z,0,x<0?Math.PI/2:-Math.PI/2);await page.evaluate(()=>window.__exit3.state.immuneUntil=window.__exit3.state.time+4);await press('KeyW',2200);check(id+' kan nås genom sin korridordörr',(await state()).zone===id,(await state()).player)}
await place(-15,39,0,Math.PI/2);await press('KeyW',4000);check('Klassrummets yttervägg går inte att gå igenom',(await state()).player.x>-25.1);
await place(-15,36);await page.locator('#pauseButton').tap();const t=(await state()).time;await step(5000);check('Paus stoppar spelets tid',(await state()).mode==='paused'&&(await state()).time===t);await page.locator('#resume').tap();await step(50);check('Fortsätt startar tiden igen',(await state()).time>t);
await place(0,10);await page.evaluate(()=>{const s=window.__exit3.state;s.immuneUntil=0;s.answers.math[0]='42';s.monsters.enogat.x=0;s.monsters.enogat.z=10.4});await step(30);check('Enögat kan fånga spelaren i korridoren',(await state()).catches===1&&(await state()).zone==='math');check('Fångad spelare behåller skrivna svar',(await state()).answers.math[0]==='42');
await place(30,-30,1.8);await page.evaluate(()=>{const s=window.__exit3.state;s.gym.phase='seek';s.gym.timer=30;s.immuneUntil=0;s.monsters.spider.x=30;s.monsters.spider.z=-34});await step(1100);check('Åttaben upptäcker en synlig spelare även ovanför golvet',(await state()).gym.phase==='count'&&(await state()).catches===2,{gym:(await state()).gym,catches:(await state()).catches});check('Hittad spelare får ny 30-sekunders räkning',(await state()).gym.timer>29);
// Inspect hidden safe positions; no monster is allowed into a classroom.
await place(-7,10);await page.evaluate(()=>{const s=window.__exit3.state;s.monsters.enogat.x=-3;s.monsters.enogat.z=10;s.immuneUntil=0});const n=(await state()).catches;await step(8000);check('Enögat stannar i korridoren',(await state()).catches===n&&(await state()).monsters.enogat.x>=-4.3);
// Actual opponent kicks score, and a loss confers no boost or subject credit.
await place(25,119);await page.evaluate(()=>window.__exit3.state.ball='yard');await press('KeyE');for(let i=0;i<3;i++){await step(1400);await place(36,124);await page.evaluate(()=>{const s=window.__exit3.state;s.football.ball.x=25;s.football.ball.z=130;s.football.ball.vx=0;s.football.ball.vz=0;s.monsters.snabbis.x=25;s.monsters.snabbis.z=129.3});await step(700)}check('Snabbis kan vinna fotboll till tre',(await state()).football.snabbis===3&&!(await state()).football.active);check('Förlust ger ingen fartökning',(await state()).boostRemaining===0);check('Fotboll gör inte idrotten klar',!(await state()).done.gym);
// Keyboard-sized viewport and portrait keep fields and back controls usable.
await place(-15,31);await press('KeyE');await page.setViewportSize({width:1180,height:430});await page.locator('#answer-2').fill('63');await page.screenshot({path:out+'/keyboard-layout.png'});const back=await page.locator('#closeBoard').boundingBox();check('Tavlans tillbaka-knapp är synlig med minskad tangentbordsyta',back.y>=0&&back.y+back.height<=430);await page.locator('#answer-0').fill('42');await page.locator('#answer-1').fill('32');check('Inmatning fungerar med minskad skärmyta',(await state()).done.math);await page.locator('#closeBoard').tap();await page.setViewportSize({width:820,height:1180});await page.screenshot({path:out+'/portrait.png'});
const controls=await page.locator('#touch button').evaluateAll(nodes=>nodes.map(n=>{const r=n.getBoundingClientRect();return {x:r.x,y:r.y,w:r.width,h:r.height}}));check('Pekknappar hålls inom stående iPad-format',controls.every(r=>r.x>=0&&r.y>=0&&r.x+r.w<=820&&r.y+r.h<=1180));check('Pekknapparna överlappar inte',controls.every((a,i)=>controls.every((b,j)=>i===j||a.x+a.w<=b.x||b.x+b.w<=a.x||a.y+a.h<=b.y||b.y+b.h<=a.y)));
await page.locator('#pauseButton').tap();await page.locator('#restart').tap();await step(50);const reset=await state();check('Omstart rensar ämnen, svar och föremål',Object.keys(reset.done).length===0&&reset.answers.math.every(x=>x==='')&&!reset.inventory.book&&!reset.inventory.ball&&!reset.inventory.water);check('Omstart återställer minispel och stängd flykt',reset.gym.phase==='balls'&&reset.gym.hits===0&&!reset.gateOpen&&!reset.football.active);
// Both engines render the same real world; this is an emulated viewport, not a physical iPad.
await page.setViewportSize({width:1180,height:820});await place(0,83,0,Math.PI);await page.screenshot({path:out+'/yard-overview.png'});await place(0,-64,0,Math.PI);await page.evaluate(()=>{window.__exit3.state.done=Object.fromEntries(['math','swedish','english','social','science','gym'].map(k=>[k,true]));window.__exit3.checkProgress()});await step(20);await page.screenshot({path:out+'/mouth.png'});
await page.goto(new URL('../',base).href,{waitUntil:'networkidle'});check('Portalen har länken till trean',await page.locator('a[href^="where-is-exit-3/"]').count()===1);check('Portalen behåller ettan och tvåan',await page.locator('a[href^="where-is-exit/"]').count()===1&&await page.locator('a[href^="where-is-exit-2/"]').count()===1);await page.locator('a[href^="where-is-exit-3/"]').tap();await page.waitForFunction(()=>!!window.render_game_to_text);check('Portallänken öppnar det nya spelet',(await state()).version==='20261009-gym10-2');check('Inga webbläsarfel',errors.length===0,errors);
await fs.writeFile(out+'/report.json',JSON.stringify({engine:process.env.ENGINE||'chromium',base,checks,errors},null,2));await browser.close();console.log(`RESULT ${checks.filter(c=>c.pass).length}/${checks.length}`);if(checks.some(c=>!c.pass))process.exitCode=1;
