import {SpaceView} from './view.js?v=20261003-explore';
import {PLANET,wrapBody,planetDelta,shipRooms,shipCovers,shipObstacles,shipWalkable,shipPath,shipLineClear,segmentHit,SHIP_ENTRY,SPACE_DOCK} from './world.js?v=20261003-explore';
'use strict';
const canvas=document.querySelector('canvas'),view=new SpaceView(canvas);
const $=s=>document.querySelector(s), keys=new Set();
const stick={id:null,x:0,y:0};
const planets=['Zorax','Lumora','Kryon','Vexara','Nebulis','Jorden'];
const colors=['#dd914b','#af83df','#68cddd','#e8b6db','#9aa0e5','#56bb93'];
const foods=['Raketpizza','Månpannkakor','Meteorittköttbullar','Stjärnpasta','Rymdtacos'];
const drinks=['Månvatten','Soljuice','Mars-saft','Stjärnmjölk','Meteoritchoklad'];
const names=['Nova','Leo','Mira','Sam','Alex','Kim','Lo','Robin','Charlie','Max'];
let state={started:false,scene:'station',player:{x:600,y:400,hp:6,weapon:'none',inventory:[],aim:-Math.PI/2,pitch:0,jumpHeight:0,jumpVelocity:0},time:0,idle:0,dialog:null,rockets:[{id:0,place:'yard',crew:[],doorOpen:false,armory:{swordTaken:false,pistolOwners:[]}},{id:1,place:'yard',crew:[],doorOpen:false,armory:{swordTaken:false,pistolOwners:[]}},{id:2,place:'yard',crew:[],doorOpen:false,armory:{swordTaken:false,pistolOwners:[]}}],rocket:null,floor:0,destination:'Rymden',pilot:null,companions:[],enemies:[],shots:[],effects:[],surveyed:[],packed:false,repaired:false,sensor:false,food:null,drink:null,filling:null,servedMeal:null,seated:false,cover:null,peek:0,blockedShots:0,shipEnemies:null,planetLaps:{x:0,y:0},dummyHits:[0,0],training:false,cannon:false,glass:false,kills:0,route:[],nextInvite:45};
let pendingTrip='Rymden',toastTime=0,shootCooldown=0,enemyCounter=0,uiSignature='';
const rooms=[{name:'Huvudrum',x:600,y:320,r:142},{name:'Matsal',x:260,y:320,r:128},{name:'Träningsrum',x:940,y:320,r:128},{name:'Pistolrum',x:600,y:100,r:92}];
const bots=[{x:535,y:365,name:'Nova',dialog:'trip'},{x:670,y:375,name:'Leo',dialog:'planet'},{x:550,y:245,name:'Mira',dialog:'pack'},{x:650,y:245,name:'Sam',dialog:'sensor'},{x:400,y:645,name:'Alex',dialog:'repair'},{x:220,y:350,name:'Kim',dialog:'food'},{x:980,y:350,name:'Lo',dialog:'train'},{x:1040,y:310,name:'Robin'},{x:285,y:260,name:'Charlie'},{x:600,y:80,name:'Max'}];
function notify(t){$('#toast').textContent=t;$('#toast').classList.add('show');toastTime=5;}
function closeModal(){state.dialog=null;$('#modal').hidden=true;uiSignature='';}
function modal(tag,title,copy,options){keys.clear();stopStick();look=null;state.route=[];state.dialog=title;$('#modal-tag').textContent=tag;$('#modal-title').textContent=title;$('#modal-copy').textContent=copy;$('#choices').replaceChildren();for(const [label,fn] of options){const b=document.createElement('button');b.textContent=label;b.onclick=()=>{closeModal();fn();render();updateUI();};$('#choices').append(b);}$('#modal').hidden=false;}
function info(t,c){modal('KAPTENENS LOGG',t,c,[['Fortsätt',()=>{}]]);}
function dialogue(type){
 const no=['Nej',()=>{}];
 if(type==='trip')modal('NOVA · ASTRONAUTKOMPIS','Jag är redo, kapten. Ska vi åka till rymden nu?','Två kompisar följer med dig.',[['Ja',()=>driveQuestion('Rymden')],no,['Hej då',()=>{}]]);
 if(type==='planet')modal('LEO · ASTRONAUTKOMPIS','Kapten, jag har upptäckt en planet! Vill du följa med och utforska den?','Leo har upptäckt Zorax.',[['Ja',()=>driveQuestion('Zorax')],no]);
 if(type==='drive')modal('ASTRONAUTKOMPIS','Kapten, vill du köra raketen den här gången?','Ni är tre personer i raketen, inklusive piloten.',[['Nej, du får köra',()=>depart(pendingTrip,'Nova')],['Ja, jag vill köra',()=>depart(pendingTrip,'Kapten')]]);
 if(type==='pack')modal('MIRA · ASTRONAUTKOMPIS','Kapten, ska vi börja packa utrustningen?','',[no,['Ja, packa utrustningen. Säg till mig när du är redo.',()=>{state.packed=true;notify('Utrustningen är packad, kapten. Laserpistolerna är klara.');equip('pistol');}]]);
 if(type==='sensor')modal('SAM · ASTRONAUTKOMPIS','Kapten, sensorerna visar något konstigt där ute – ska vi undersöka det?','',[no,['Vi kollar upp vad sensorerna säger.',()=>{state.sensor=true;notify('Sensorn visar okända små skepp. Kontrollera pistolrummet.');}]]);
 if(type==='repair')modal('ALEX · ASTRONAUTKOMPIS','Kapten, raketen behöver lagas. Kan du hjälpa mig?','',[['Bygg inte upp den',()=>{}],['Ja, bygg upp den du. Jag tar hjälp av några andra.',()=>{state.repaired=true;notify('Alex och de andra har lagat raketens panel.');}]]);
 if(type==='food')modal('KIM · ASTRONAUTKOMPIS','Kapten, maten är klar! Vill du komma och äta med oss?','',[['Ja',()=>{state.player.x=235;state.player.y=355;mealMenu();}],no]);
 if(type==='train')modal('LO · ASTRONAUTKOMPIS','Kapten! Vill du träna med mig i träningsrummet?','',[no,['Ja, jag följer med',startTraining]]);
}
function driveQuestion(dest){pendingTrip=dest;dialogue('drive');}
function freeRocket(){return state.rockets.find(r=>r.place==='yard'&&r.crew.length===0);}
function equip(w){if(!state.player.inventory.includes(w))state.player.inventory.push(w);state.player.weapon=w;notify(w==='pistol'?'Laserpistol utrustad. Sikta och skjut.':'Lasersvärd utrustat. Bara kaptenen har svärd.');}
function depart(dest,pilot){resetJump();const reinforcements=state.companions.filter(c=>c.rocket!==undefined);let r=state.rocket!==null?state.rockets[state.rocket]:freeRocket();if(!r){notify('Ingen raket finns kvar på gården.');return;}r.crew=['Kapten','Nova','Leo'];r.doorOpen=false;r.place=dest;state.rocket=r.id;state.pilot=pilot;state.destination=dest;state.companions=r.crew.slice(1).map((name,i)=>({name,hp:4,armed:r.armory.pistolOwners.includes(name),x:500+i*90,y:400,cd:1+i})).concat(reinforcements);reinforcements.forEach(c=>state.rockets[c.rocket].place=dest);state.seated=false;state.scene='rocket';state.floor=2;state.player.pitch=0;state.player.aim=-Math.PI/2;state.player.x=600;state.player.y=350;state.enemies=[];state.shots=[];state.training=false;notify(`${pilot} kör. Ni har nått ${dest}. Gå ner till mittenrummet för kartan.`);}
function board(id){resetJump();const r=state.rockets[id];if(r.place!=='yard'){notify('Den raketen är redan ute i rymden.');return;}if(r.crew.length&&r.crew[0]!=='Kapten'){notify('Raketen är full: tre personer inklusive pilot.');return;}r.crew=['Kapten','Nova','Leo'];state.rocket=id;state.companions=r.crew.slice(1).map((name,i)=>({name,hp:4,armed:r.armory.pistolOwners.includes(name),x:520+i*120,y:420,cd:1}));state.seated=false;state.scene='rocket';state.floor=0;state.player.pitch=0;state.player.aim=-Math.PI/2;state.destination='Jorden';state.player.x=600;state.player.y=470;notify('Ni är tre ombord. Trapporna leder mellan alla våningar.');}
function rocketArmory(){const r=state.rockets[state.rocket];return [...(!r.armory.swordTaken&&!state.player.inventory.includes('sword')?[{x:760,y:460,kind:'weapon',weapon:'sword',label:'Ta raketens lasersvärd',fn:()=>{if(r.armory.swordTaken)return;r.armory.swordTaken=true;equip('sword');}}]:[]),...r.crew.slice(1).flatMap((name,i)=>r.armory.pistolOwners.includes(name)?[]:[{x:805+i*45,y:460,kind:'weapon',weapon:'crew-pistol',label:'Ge '+name+' raketens laserpistol',fn:()=>{if(r.armory.pistolOwners.includes(name))return;r.armory.pistolOwners.push(name);const c=state.companions.find(c=>c.name===name&&(c.rocket===undefined||c.rocket===r.id));if(c)c.armed=true;notify(name+' har fått sin laserpistol. Den tillhör kompisen.');}}])];}
function floorTo(n){resetJump();state.seated=false;state.floor=n;state.player.x=600;state.player.y=425;state.companions.filter(c=>c.rocket===undefined||c.rocket===state.rocket).forEach((c,i)=>{c.x=520+i*160;c.y=430;});}
function mapMenu(){modal('RYMDKARTAN','Välj destination','Markera en planet. Starta sedan från cockpit högst upp.',[...['Rymden',...planets].map(p=>[p,()=>{state.destination=p;notify(`Destination markerad: ${p}. Gå till cockpit och starta.`);}]),['Stäng',()=>{}]]);}
function launch(){if(state.rockets[state.rocket].place==='yard'){driveQuestion(state.destination==='Jorden'?'Rymden':state.destination);return;}const r=state.rockets[state.rocket];r.doorOpen=false;r.place=state.destination;state.companions.filter(c=>c.rocket!==undefined).forEach(c=>state.rockets[c.rocket].place=state.destination);state.enemies=[];state.shots=[];notify(`Framme vid ${state.destination}. Gå ner till utgången för att utforska.`);}
function summon(){const active=state.rockets[state.rocket];if(active.place==='yard'||active.place==='Jorden'){notify('Datorn kallar på hjälp när du är ute i rymden.');return;}const r=freeRocket();if(!r){notify('Ingen raket kvar på gården – ingen hjälp kan komma.');return;}const index=r.id*3;r.crew=[names[index+2]||'Kim',names[index+3]||'Lo',names[index+4]||'Robin'];r.place=active.place;r.armory.pistolOwners=r.crew.slice(1);state.companions.push(...r.crew.map((name,i)=>({name,hp:4,armed:r.armory.pistolOwners.includes(name),x:480+i*80,y:470,cd:i+1,rocket:r.id})));notify(`Tre kompisar kommer i raket ${r.id+1}. Den har tre personer inklusive pilot.`);}
function exitRocket(){resetJump();let dest=state.rockets[state.rocket].place;if(dest==='yard'||dest==='Jorden'){returnStation(false);return;}state.seated=false;state.scene=dest==='Rymden'?'space':'planet';state.player.x=240;state.player.y=430;state.player.aim=0;state.player.pitch=0;state.companions.forEach((c,i)=>{c.x=160+(i%3)*45;c.y=510+Math.floor(i/3)*45;});state.shots=[];state.enemies=[];if(state.scene==='planet')spawnAliens(dest);else for(let i=0;i<4;i++)spawnEnemy('ship',750+i*90,160+i*140);notify(dest==='Rymden'?'Du svävar i rymden. Utforska eller gå tillbaka till raketen.':`${dest}: aliens är tysta. Undersök planetens fyr för att kartlägga den.`);}
function enterRocket(){resetJump();state.seated=false;state.scene='rocket';state.floor=0;state.player.x=600;state.player.y=440;state.shots=[];state.enemies=[];}
function returnStation(rescue){resetJump();state.seated=false;state.scene='station';state.player.x=600;state.player.y=530;state.shots=[];state.enemies=[];state.training=false;state.cannon=false;state.glass=false;state.companions=[];state.rocket=null;state.rockets.forEach(r=>{r.place='yard';r.crew=[];r.doorOpen=false;});if(rescue)state.player.hp=6;notify(rescue?'Räddad tillbaka till stationen. Alla raketer och kompisar är säkra.':'Tillbaka på Jorden. De andra raketerna återvänder också till gården.');}
function mealMenu(){modal('MATSAL · KÖK OCH KASSA','Vad vill du äta?','Välj mat, dryck och sedan ett bord.',[...foods.map(f=>[f,()=>{state.food=f;if(f==='Rymdtacos')modal('FYLLNING','Välj fyllning','',[...['Bönor','Ost','Grönsaker'].map(t=>[t,()=>{state.filling=t;drinkMenu();}])]);else{state.filling=null;drinkMenu();}}]),['Hej då',()=>{}]]);}
function drinkMenu(){modal('MATSAL','Vad vill du dricka?',state.food,drinks.map(d=>[d,()=>{state.drink=d;notify('Maten är hämtad. Sätt dig vid ett bord för att äta.');}]));}
function eat(){if(!state.food||!state.drink){notify('Hämta först mat och dryck i kassan.');return;}state.servedMeal={food:state.food,drink:state.drink,filling:state.filling};state.seated=true;state.player.x=285;state.player.y=395;state.player.aim=-Math.PI/2;state.player.pitch=-.15;state.player.hp=6;info('Du äter med kompisarna',`${state.food}${state.filling?' med '+state.filling:''} och ${state.drink}. Alla dina sex liv är återställda.`);state.food=null;state.drink=null;}
function startTraining(){resetJump();state.seated=false;state.scene='station';state.player.x=915;state.player.y=390;state.training=true;equip('pistol');state.companions=[{name:'Lo',hp:4,x:890,y:385,cd:2,armed:true}];state.enemies=[];state.shots=[];spawnEnemy('robot',910,270);spawnEnemy('robot',990,270);notify('Du och Lo tränar mot två robotar.');}
function trainingEnd(win){state.training=false;state.enemies=[];state.shots=[];state.companions=[];state.player.hp=6;modal('TRÄNINGEN ÄR KLAR',win?'Yippie, vi vann!':'Bra kört.','Kompisen säger:',[[win?'Aa, bra.':'Detsamma.',()=>notify('Träningen är klar. Ni kan träna igen.')]]);}
function cannonMode(){resetJump();state.seated=false;state.scene='cannon';state.player.x=600;state.player.y=660;state.cannon=true;state.glass=true;state.enemies=[];state.shots=[];for(let i=0;i<5;i++)spawnEnemy('ship',170+i*205,150+(i%2)*130);notify('Glaset öppnas. Sikta på skeppen och skjut med laserkanonen.');}
function spawnEnemy(type,x,y){state.enemies.push({id:++enemyCounter,type,x,y,hp:4,t:enemyCounter,cd:1.8+(enemyCounter%3)*.4,baseX:x,baseY:y});}
function spawnAliens(p){for(let i=0;i<5;i++)spawnEnemy(p,560+i*105,180+(i%3)*170);spawnEnemy('ship',920,120);spawnEnemy('ship',770,650);}
const delta=(a,b)=>state.scene==='planet'?planetDelta(a,b):{x:b.x-a.x,y:b.y-a.y};
const angleTo=(a,b)=>{const v=delta(a,b);return Math.atan2(v.y,v.x);};
const d=(a,b)=>{const v=delta(a,b);return Math.hypot(v.x,v.y);};
function enterShip(){resetJump();state.scene='enemyship';state.seated=false;state.player.x=260;state.player.y=180;state.player.aim=Math.PI/2;state.player.pitch=0;state.shots=[];state.enemies=state.shipEnemies||shipRooms.flatMap(r=>[{id:++enemyCounter,type:'guard',hp:4,x:r.x+90,y:r.y+65,baseX:r.x+90,baseY:r.y+65,t:0,cd:2.6,room:r.id},{id:++enemyCounter,type:'guard',hp:4,x:r.x-95,y:r.y-55,baseX:r.x-95,baseY:r.y-55,t:1,cd:3.1,room:r.id}]);state.companions.forEach((c,i)=>{c.x=225+i*70;c.y=160;c.path=[];c.pathTime=0;});notify('Fiendeskeppet: 16 rum. Slå nära markerad vägg eller tunna för skydd. Rörelse, Hoppa eller Lämna skydd lämnar skyddet.');}
function leaveShip(){state.shipEnemies=state.enemies;resetJump();state.scene='space';state.player.x=760;state.player.y=430;state.player.aim=Math.PI;state.player.pitch=0;state.enemies=[];state.shots=[];state.companions.forEach((c,i)=>{c.x=710+i*30;c.y=490;c.path=[];});notify('Tillbaka i rymden. Raketen och planetresorna väntar.');}
function spaceMap(){modal('RYMDRESOR','Res med raketen','Välj planet. Ni går ombord och flyger med er egen raket.',[...planets.map(name=>[name,()=>{enterRocket();state.floor=2;state.player.x=600;state.player.y=350;state.destination=name;launch();}]),['Stäng',()=>{}]]);}
function takeCover(o){if(state.cover===o.id){state.cover=null;state.peek=0;notify('Du lämnar skyddet.');return;}const p=state.player;if(o.r){const a=Math.atan2(p.y-o.y,p.x-o.x);const x=o.x+Math.cos(a)*(o.r+19),y=o.y+Math.sin(a)*(o.r+19);if(shipWalkable(x,y)){p.x=x;p.y=y;}}else{const y=o.y+(p.y>=o.y?1:-1)*(o.h/2+20),x=Math.max(o.x-o.w/2+8,Math.min(o.x+o.w/2-8,p.x));if(shipWalkable(x,y)){p.x=x;p.y=y;}}state.cover=o.id;state.peek=0;state.seated=false;resetJumpHeight();notify('I skydd bakom '+(o.type==='wall'?'väggen':'tunnan')+'. Slå: kika och skjut. Gå, hoppa eller välj Lämna skydd.');}
function resetJumpHeight(){state.player.jumpHeight=0;state.player.jumpVelocity=0;}
function points(){if(state.scene==='station')return [
 ...bots.filter(b=>b.dialog).map(b=>({x:b.x,y:b.y,label:`Prata med ${b.name}`,fn:()=>dialogue(b.dialog)})),
 {x:600,y:320,label:'Jordhologram',fn:()=>info('Jordhologrammet',`Kartlagda planeter: ${state.surveyed.length}/5. Du är kapten på stationen på Jorden.`)},
 {x:210,y:245,label:'Beställ mat',fn:mealMenu},{x:285,y:365,label:'Sitt och ät',fn:eat},
 {x:930,y:240,kind:'weapon',weapon:'pistol',label:'Ta laserpistol',fn:()=>equip('pistol')},{x:990,y:240,kind:'weapon',weapon:'sword',label:'Ta lasersvärd',fn:()=>equip('sword')},
 {x:875,y:320,label:'Träna ensam',fn:()=>{state.training=false;state.enemies=[];spawnEnemy('robot',990,300);equip('pistol');notify('En robot rör sig och skjuter tillbaka.');}},
 {x:600,y:100,label:'Styr laserkanonen',fn:cannonMode},
 ...state.rockets.map((r,i)=>({x:500+i*100,y:665,kind:'door',label:r.place==='yard'?(r.doorOpen?`Gå in i raket ${i+1}`:`Öppna dörr till raket ${i+1}`):`Raket ${i+1} är ute`,fn:()=>rocketDoor(i,()=>board(i))}))];
 if(state.scene==='rocket')return [
 ...(state.floor<2?[{x:820,y:340,label:'Trappa upp',fn:()=>floorTo(state.floor+1)}]:[]),
 ...(state.floor>0?[{x:380,y:340,label:'Trappa ner',fn:()=>floorTo(state.floor-1)}]:[]),
 ...(state.floor===0?[{x:600,y:570,kind:'door',label:state.rockets[state.rocket].doorOpen?'Gå ut ur raketen':'Öppna utgången',fn:()=>rocketDoor(state.rocket,exitRocket)}]:[]),
 ...(state.floor===1?[...rocketArmory(),{x:600,y:475,label:'Sitt vid samtalsbordet',fn:()=>{state.seated=true;state.player.x=600;state.player.y=535;state.player.aim=-Math.PI/2;state.player.pitch=0;state.companions.filter(c=>c.rocket===undefined||c.rocket===state.rocket).forEach((c,i)=>{c.x=540+i*120;c.y=485;});notify('Du sitter med Nova och Leo. Prata med dem från bordet.');}},...state.companions.filter(c=>c.rocket===undefined||c.rocket===state.rocket).map(c=>({x:c.x,y:c.y,label:`Prata med ${c.name}`,fn:()=>dialogue(c.name==='Nova'?'trip':'planet')})),{x:520,y:260,label:'Rymdkarta',fn:mapMenu},{x:700,y:260,label:'Kalla på tre kompisar',fn:summon}]:[]),
 ...(state.floor===2?[{x:600,y:250,label:'Starta / kör till destination',fn:launch}]:[])];
 if(state.scene==='enemyship')return [{...SHIP_ENTRY,kind:'door',label:'Lämna fiendeskeppet',fn:leaveShip},...shipCovers.map(o=>({...o,kind:'cover',label:(state.cover===o.id?'Lämna skydd':o.type==='barrel'?'Ta skydd bakom tunna':'Ta skydd bakom vägg')+' · '+shipRooms[Number(o.id.split('-')[1])].name,fn:()=>takeCover(o)}))];
 if(state.scene==='planet'||state.scene==='space')return [{x:150,y:380,kind:'door',label:state.rockets[state.rocket].doorOpen?'Tillbaka till raketen':'Öppna raketdörren',fn:()=>rocketDoor(state.rocket,enterRocket)},...(state.scene==='planet'?[{x:1060,y:430,label:'Undersök planeten',fn:()=>{const p=state.rockets[state.rocket].place;if(!state.surveyed.includes(p))state.surveyed.push(p);notify(`${p} är kartlagd! ${state.surveyed.length}/5 planeter undersökta.`);}}]:[{...SPACE_DOCK,kind:'door',label:'Gå in i fiendeskeppet',fn:enterShip}])];
 if(state.scene==='cannon')return [{x:600,y:660,label:'Lämna laserkanonen',fn:()=>{state.scene='station';state.player.x=600;state.player.y=140;state.cannon=false;state.glass=false;state.enemies=[];state.shots=[];}}];return [];}
function nearest(){return points().filter(p=>d(p,state.player)<105).sort((a,b)=>d(a,state.player)-d(b,state.player));}
function use(){if(!state.dialog){const p=nearest()[0];if(p)p.fn();else notify('Gå närmare en kompis, dörr eller sak.');}}
function goRoom(name){if(state.training||state.enemies.length){notify('Avsluta träningen först, eller lämna träningsrummet till fots.');return;}const p=state.player,route=[];if(p.y>500)route.push({x:p.x,y:540},{x:600,y:540},{x:600,y:420});else if(p.x<430)route.push({x:260,y:320},{x:500,y:320},{x:500,y:380},{x:600,y:420});else if(p.x>770)route.push({x:940,y:320},{x:700,y:320},{x:700,y:380},{x:600,y:420});else if(p.y<330)route.push({x:660,y:270},{x:660,y:370},{x:600,y:420});else route.push({x:600,y:420});const routes={Huvudrum:[],Matsal:[{x:500,y:380},{x:500,y:320},{x:260,y:320},{x:260,y:355}],Träningsrum:[{x:700,y:380},{x:700,y:320},{x:940,y:320},{x:940,y:355}],Pistolrum:[{x:660,y:370},{x:660,y:270},{x:600,y:230},{x:600,y:135}],Gården:[{x:600,y:540}]};state.route=route.concat(routes[name]);state.player.pitch=name==='Gården'?.3:0;}
function walkable(x,y){if(state.scene==='planet')return true;if(state.scene==='enemyship')return shipWalkable(x,y);if(state.scene==='station'&&(Math.hypot(x-600,y-320)<34||state.rockets.some((r,i)=>r.place==='yard'&&Math.hypot(x-(500+i*100),y-710)<38)))return false;if(state.scene==='station')return rooms.some(r=>Math.hypot(x-r.x,y-r.y)<r.r-17)||(x>250&&x<950&&Math.abs(y-320)<32)||(Math.abs(x-600)<33&&y>90&&y<630)||(x>170&&x<1030&&y>520&&y<745);if(state.scene==='rocket')return x>315&&x<885&&y>210&&y<600;if(state.scene==='cannon')return false;return x>30&&x<1170&&y>60&&y<745;}
function coverEye(){const o=shipCovers.find(o=>o.id===state.cover);return o&&state.peek>0?o.height+.6:state.cover?1.05:1.65;}
function projectile(owner,x,y,angle,target){const pitch=owner==='captain'?state.player.pitch:target?Math.atan2((target===state.player?coverEye():1.65)-1.65,d({x,y},target)/20):0,scale=state.scene==='rocket'?50:20;state.shots.push({owner,x,y,h:(state.scene==='rocket'?state.floor*4:0)+(owner==='captain'?coverEye():1.65)+(owner==='captain'?state.player.jumpHeight:0),vh:Math.sin(pitch)*560/scale,vx:Math.cos(angle)*Math.cos(pitch)*560,vy:Math.sin(angle)*Math.cos(pitch)*560,life:1.9});}
function resetJump(){state.cover=null;state.peek=0;state.player.jumpHeight=0;state.player.jumpVelocity=0;}
function jump(){if(!state.started||state.dialog||state.player.jumpHeight>0)return;state.cover=null;state.peek=0;state.seated=false;state.player.jumpVelocity=6.2;}
function nearbyFriend(){const friends=state.scene==='station'?bots:state.scene==='rocket'||state.scene==='planet'||state.scene==='space'||state.scene==='enemyship'?state.companions.filter(c=>c.hp>0&&(state.scene!=='rocket'||c.rocket===undefined||c.rocket===state.rocket)):[];return friends.filter(c=>d(c,state.player)<(state.scene==='rocket'?80:40)).sort((a,b)=>d(a,state.player)-d(b,state.player))[0];}
function rocketDoor(id,enter){const r=state.rockets[id];if(state.scene==='station'&&r.place!=='yard'){notify('Den raketen är redan ute i rymden.');return;}if(r.crew.length&&r.crew[0]!=='Kapten'){notify('Raketen är full: tre personer inklusive pilot.');return;}if(!r.doorOpen){r.doorOpen=true;notify('Raketdörren öppnas. Tryck Slå igen för att gå igenom.');}else enter();}
function contextAction(){if(!state.started||state.dialog)return true;if(state.scene==='enemyship'&&state.cover){attack();return false;}const target=points().filter(p=>(p.kind==='weapon'&&!state.player.inventory.includes(p.weapon)&&d(p,state.player)<40)||(p.kind==='door'&&d(p,state.player)<(state.scene==='rocket'?80:55))).sort((a,b)=>(a.kind==='weapon'?0:1)-(b.kind==='weapon'?0:1)||d(a,state.player)-d(b,state.player))[0];if(target){keys.delete('Space');keys.delete('KeyQ');target.fn();return true;}const friend=nearbyFriend();if(state.scene==='enemyship'){if(state.cover){attack();return false;}const cover=shipCovers.filter(o=>d(o,state.player)<(o.r?o.r+40:55)).sort((a,b)=>d(a,state.player)-d(b,state.player))[0];if(cover&&(!friend||d(cover,state.player)-(cover.r||20)<d(friend,state.player))){takeCover(cover);keys.delete('Space');keys.delete('KeyQ');return true;}}if(friend){const type=friend.dialog||({Nova:'trip',Leo:'planet',Mira:'pack',Sam:'sensor',Alex:'repair',Kim:'food',Lo:'train',Robin:'train',Charlie:'food',Max:'sensor'}[friend.name]||'trip');dialogue(type);$('#modal-tag').textContent=friend.name.toUpperCase()+' · ASTRONAUTKOMPIS';return true;}attack();return false;}
function attack(sword=false){if(!state.started||state.dialog||shootCooldown>0)return;const p=state.player;if(state.scene==='cannon'){projectile('captain',600,620,p.aim);shootCooldown=.18;return;}if(state.cover&&p.weapon!=='none')state.peek=.48;if(sword||p.weapon==='sword'){if(!p.inventory.includes('sword')){notify('Hämta ett vapen i träningsrummet.');return;}if(sword)p.weapon='sword';state.effects.push({type:'sword',x:p.x,y:p.y,t:.2});for(const e of state.enemies)if(d(e,p)<48)hitEnemy(e);shootCooldown=.4;}else if(p.weapon==='pistol'){projectile('captain',p.x,p.y,p.aim);state.effects.push({type:'fire',x:p.x,y:p.y,t:.12});shootCooldown=.24;}else notify('Hämta en laserpistol i träningsrummet.');}
function hitEnemy(e){if(e.hp<=0)return;e.hp--;state.effects.push({type:'spark',x:e.x,y:e.y,t:.2});if(e.hp===0)state.kills++;}
function damage(who){if(who===state.player&&state.cover&&state.peek<=0)return;who.hp=Math.max(0,who.hp-1);state.effects.push({type:'hit',x:who.x,y:who.y,t:.3});if(who===state.player&&who.hp===0){if(state.training)trainingEnd(false);else returnStation(true);}}
function update(dt){if(!state.started||state.dialog)return;state.time+=dt;state.peek=Math.max(0,state.peek-dt);shootCooldown=Math.max(0,shootCooldown-dt);toastTime-=dt;if(toastTime<=0)$('#toast').classList.remove('show');const p=state.player;p.jumpHeight+=p.jumpVelocity*dt;if(p.jumpHeight>0)p.jumpVelocity-=14*dt;else{p.jumpHeight=0;p.jumpVelocity=0;}
 if(keys.has('KeyJ'))p.aim-=1.8*dt;if(keys.has('KeyL'))p.aim+=1.8*dt;
 let strafe=(keys.has('ArrowRight')||keys.has('KeyD')?1:0)-(keys.has('ArrowLeft')||keys.has('KeyA')?1:0),forward=(keys.has('ArrowUp')||keys.has('KeyW')?1:0)-(keys.has('ArrowDown')||keys.has('KeyS')?1:0);
  strafe+=stick.x;forward-=stick.y;
 let dx=Math.cos(p.aim)*forward+Math.cos(p.aim+Math.PI/2)*strafe,dy=Math.sin(p.aim)*forward+Math.sin(p.aim+Math.PI/2)*strafe;
 if(dx||dy){state.route=[];}else if(state.route.length){const t=state.route[0];if(d(p,t)<7)state.route.shift();else{dx=t.x-p.x;dy=t.y-p.y;p.aim=Math.atan2(dy,dx);}}
 const len=Math.hypot(dx,dy);if(len){state.seated=false;state.cover=null;state.peek=0;}state.idle=len||keys.size||state.route.length?0:state.idle+dt;if(len){let nx=p.x+dx/len*Math.min(1,len)*190*dt,ny=p.y+dy/len*Math.min(1,len)*190*dt;if(walkable(nx,p.y))p.x=nx;if(walkable(p.x,ny))p.y=ny;if(state.scene==='planet'){state.planetLaps.x+=Math.floor(p.x/PLANET.width);state.planetLaps.y+=Math.floor(p.y/PLANET.height);wrapBody(p);}}
 if(keys.has('Space')||keys.has('KeyQ'))contextAction();
 state.companions.forEach((c,i)=>{if(c.hp<=0)return;if(state.scene!=='rocket'){let tx=p.x-45+(i%3)*40,ty=p.y+55+Math.floor(i/3)*35;if(state.scene==='enemyship'){tx=p.x-Math.cos(p.aim)*55+Math.cos(p.aim+Math.PI/2)*(i%3-1)*35;ty=p.y-Math.sin(p.aim)*55+Math.sin(p.aim+Math.PI/2)*(i%3-1)*35;c.pathTime=(c.pathTime||0)-dt;if(!shipLineClear(c,{x:tx,y:ty})){if(c.pathTime<=0){c.path=shipPath(c,p);c.pathTime=.8;}if(c.path?.length){if(d(c,c.path[0])<15)c.path.shift();if(c.path.length){tx=c.path[0].x;ty=c.path[0].y;}}}else c.path=[];}const v=delta(c,{x:tx,y:ty}),dd=Math.hypot(v.x,v.y);if(dd>(state.scene==='enemyship'?8:25)){const nx=c.x+v.x/dd*120*dt,ny=c.y+v.y/dd*120*dt;if(walkable(nx,c.y))c.x=nx;if(walkable(c.x,ny))c.y=ny;if(state.scene==='planet')wrapBody(c);}}c.cd-=dt;const e=state.enemies.filter(e=>e.hp>0).sort((a,b)=>d(a,c)-d(b,c))[0];if(e&&d(e,c)<380)c.aim=angleTo(c,e);if(c.armed!==false&&e&&d(e,c)<380&&c.cd<=0&&(state.scene!=='enemyship'||shipLineClear(c,e))){projectile('friend',c.x,c.y,angleTo(c,e));c.cd=1.15;}});
 for(const e of state.enemies){if(e.hp<=0)continue;e.t+=dt;e.cd-=dt;const targets=[p,...state.companions.filter(c=>c.hp>0)];const t=targets.sort((a,b)=>d(a,e)-d(b,e))[0];const angle=angleTo(e,t);
 if(e.type==='guard'){const r=shipRooms[e.room],nx=e.baseX+Math.cos(e.t*.7)*12,ny=e.baseY+Math.sin(e.t*.8)*16;if(shipWalkable(nx,e.y))e.x=nx;if(shipWalkable(e.x,ny))e.y=ny;if(e.cd<=0&&d(e,t)<480 ){projectile('enemy',e.x,e.y,angle,t);e.cd=2.4;}continue;}
 if(e.type==='Nebulis'){e.x+=Math.cos(angle)*160*dt;e.y+=Math.sin(angle)*160*dt;if(d(e,t)<36&&e.cd<=0){damage(t);e.cd=1.1;}}
 else{const speed=e.type==='robot'?36:22;e.x+=Math.cos(e.t*1.3+e.id)*speed*dt;e.y+=Math.sin(e.t+e.id)*speed*dt;if(e.type==='Vexara')e.y=e.baseY+Math.sin(e.t*3)*65;if(e.type==='Lumora')e.y=e.baseY+Math.sin(e.t*2)*45;if(e.cd<=0&&(state.scene==='cannon'||d(e,t)<420)){projectile('enemy',e.x,e.y,angle);if(e.type==='Kryon')projectile('enemy',e.x+12,e.y+12,angle+.08);e.cd=e.type==='ship'?2.8:2.2;}if(e.type==='robot'&&d(e,t)<34&&e.cd>1.5){damage(t);e.cd=1.2;}}
 if(state.scene==='planet')wrapBody(e);else{e.x=Math.max(state.scene==='station'?835:300,Math.min(state.scene==='station'?1040:1130,e.x));e.y=Math.max(70,Math.min(700,e.y));}
 }
 for(const s of state.shots){const prev={x:s.x,y:s.y,h:s.h};s.x+=s.vx*dt;s.y+=s.vy*dt;s.h+=s.vh*dt;s.life-=dt;if(state.scene==='planet')wrapBody(s);if(state.scene==='enemyship'){let obstruction=null,first=Infinity;for(const o of shipObstacles){const t=segmentHit(prev,s,o);if(t!==null&&t<first&&prev.h+(s.h-prev.h)*t<=o.height){first=t;obstruction=o;}}if(obstruction){s.life=0;if(s.owner==='enemy')state.blockedShots++;state.effects.push({type:'spark',x:prev.x+(s.x-prev.x)*first,y:prev.y+(s.y-prev.y)*first,t:.2});continue;}}if(state.scene==='cannon'&&s.owner==='enemy'&&s.y>570){s.life=0;state.effects.push({type:'spark',x:s.x,y:570,t:.2});continue;}const targets=s.owner==='enemy'?[p,...state.companions]:state.enemies;for(const t of targets){const targetH=(state.scene==='rocket'?state.floor*4:0)+(t.type==='Lumora'?2.5:t.type==='Vexara'?1.8:t.type==='Nebulis'?.75:1.3)+(t===p?coverEye()-1.65+p.jumpHeight:0);if(t===p&&state.cover&&state.peek<=0)continue;if(t.hp>0&&d(s,t)<(t.type==='ship'?30:23)&&Math.abs(s.h-targetH)<(t.type==='Vexara'?1.3:t.type==='Lumora'?1.4:.95)){if(s.owner==='enemy')damage(t);else hitEnemy(t);s.life=0;break;}}
 if(state.scene==='station'&&s.owner!=='enemy'&&s.life>0&&Math.abs(s.h-1.3)<.95){for(const [i,target] of [{x:875,y:280},{x:1015,y:365}].entries())if(d(s,target)<22){s.life=0;state.dummyHits[i]++;state.effects.push({type:'spark',x:target.x,y:target.y,t:.2});break;}}
 }
 state.shots=state.shots.filter(s=>s.life>0&&(state.scene==='planet'||state.scene==='enemyship'||s.x>0&&s.x<1200&&s.y>0&&s.y<800)&&s.h>0&&s.h<20);state.effects.forEach(e=>e.t-=dt);state.effects=state.effects.filter(e=>e.t>0);state.enemies=state.enemies.filter(e=>e.hp>0);
 if(state.scene==='space'&&d(p,SPACE_DOCK)<(p.jumpHeight>.3?55:24))enterShip();
 if(state.training&&state.enemies.length===0)trainingEnd(true);
 if(state.scene==='station'&&state.enemies.length&&p.x<815){if(state.training)trainingEnd(false);else{state.enemies=[];state.shots=[];}}
 if(state.scene==='station'&&state.time>state.nextInvite&&state.idle>15&&!state.route.length&&!state.training&&d(p,{x:600,y:320})<140){const nova=bots[0],dist=d(nova,p);if(dist>45){nova.x+=(p.x-nova.x)/dist*65*dt;nova.y+=(p.y-nova.y)/dist*65*dt;}else{state.nextInvite=state.time+90;dialogue('trip');}}
}
function updateUI(){const p=state.player;$('#status').textContent=`${'♥'.repeat(p.hp)}${'♡'.repeat(6-p.hp)} · ${p.weapon==='none'?'Obeväpnad':p.weapon==='pistol'?'Laserpistol':'Lasersvärd'} · ${state.surveyed.length}/5${state.cover?(state.peek>0?' · ⚠ KIKAR / SKJUTER':' · 🛡 GÖMD'):''}`;
 const places={station:'Rymdstationen · Jorden',rocket:`Raket ${(state.rocket??0)+1} · ${['Utgång','Mittenrum','Cockpit'][state.floor]} · ${state.rocket!==null?state.rockets[state.rocket].place:''}`,planet:state.rocket!==null?state.rockets[state.rocket].place:'',space:'Rymden',enemyship:'Fiendeskeppet · '+(shipRooms.find(r=>Math.abs(p.x-r.x)<150&&Math.abs(p.y-r.y)<120)?.name||'Korridor'),cannon:'Pistolrummet · glaset öppet'};$('#location').textContent=places[state.scene];
 const ps=nearest();$('#hint').textContent=state.scene==='enemyship'?(state.cover?'I skydd · Slå: kika och skjut. Gå, hoppa eller välj Lämna skydd.':'Slå nära markerad vägg/tunna: ta skydd. Utgången finns i Dockning.'):state.scene==='planet'?`Planeten går runt. Raketen: ${Math.round(d(p,{x:150,y:420})/20)} m · gå i valfri riktning.`:state.scene==='station'?'Gå till ett rum. Prata, träna, ät eller ta en raket.':state.scene==='rocket'?`Destination: ${state.destination} · Slå tar vapen, öppnar raketdörr och pratar. E använder övriga saker.`:'Sikta på ett mål. Kompisarna hjälper till. Slå tar vapen, öppnar raketdörr och pratar. E använder övriga saker.';
 const sig=state.scene+ps.map(p=>p.label).join('|')+state.training;if(sig===uiSignature)return;uiSignature=sig;$('#actions').replaceChildren();for(const a of ps){button(a.label,a.fn);}
 if(state.scene==='space'){button('Res till planet',spaceMap);button('Hitta raketen',()=>{const a=angleTo(state.player,{x:150,y:380});state.player.aim=a;notify('Siktet pekar mot din raket.');});}if(state.scene==='planet'){button('Hitta raketen',()=>{state.player.aim=angleTo(state.player,{x:150,y:420});notify('Siktet pekar mot raketens landningsplats.');});}if(state.scene==='enemyship'){if(state.cover)button('Lämna skydd',()=>{state.cover=null;state.peek=0;});button('Skeppets karta',()=>modal('FIENDESKEPPET','16 rum och öppna korridorer','Rummen ligger i fyra rader. Utgången finns norr om Dockning (första rummet). Du är i '+(shipRooms.find(r=>Math.abs(state.player.x-r.x)<150&&Math.abs(state.player.y-r.y)<120)?.name||'en korridor')+'.',[['Fortsätt',()=>{}]]));}if(state.scene==='station'){button('Stationens karta',()=>modal('GÅNGAR','Vart vill du gå?','Kaptenen går genom stationens gångar.',[...['Huvudrum','Matsal','Träningsrum','Pistolrum','Gården'].map(n=>[n,()=>goRoom(n)]),['Stäng',()=>{}]]));button('Kompisarnas radio',()=>modal('ASTRONAUTKOMPISAR','Välj en kompis','Du kan prata med kompisarna på radion också.',bots.filter(b=>b.dialog).map(b=>[b.name,()=>dialogue(b.dialog)])));}
}
function button(label,fn){const b=document.createElement('button');b.textContent=label;b.onclick=()=>{fn();uiSignature='';updateUI();render();};$('#actions').append(b);}
function render(){view.render(state,bots,rooms);}
window.render_game_to_text=()=>JSON.stringify({coordinates:'station/space 1200×800; planets 2400×1600 wrap; enemyship x110..1670/y140..1400; simulation x/y maps to 3D X/Z at 20 units/metre (rocket: 50); floor height 4m; camera at eye height 1.65m; first-person yaw=aim',started:state.started,planetWorld:state.scene==='planet'?{...PLANET,topology:'wraparound',laps:state.planetLaps,landing:{x:150,y:420}}:null,ship:state.scene==='enemyship'?{rooms:shipRooms,covers:shipCovers,cover:state.cover,peek:state.peek,hidden:!!state.cover&&state.peek<=0,eyeHeight:coverEye(),blockedShots:state.blockedShots,entry:SHIP_ENTRY}:null,controls:{joystick:{x:stick.x,y:stick.y,active:stick.id!==null}},scene:state.scene,player:state.player,dialog:state.dialog,rocket:state.rocket,floor:state.scene==='rocket'?state.floor:null,destination:state.destination,pilot:state.pilot,rockets:state.rockets,availableRockets:state.rockets.filter(r=>r.place==='yard'&&!r.crew.length).length,companions:state.companions,visibleCompanions:state.companions.filter(c=>c.hp>0&&(state.scene!=='rocket'||c.rocket===undefined||c.rocket===state.rocket)),enemies:state.enemies,shots:state.shots,stationBots:state.scene==='station'?bots:[],nearby:nearest().map(p=>({x:p.x,y:p.y,label:p.label})),training:state.training,dummyHits:state.dummyHits,glassOpen:state.glass,seated:state.seated,surveyed:state.surveyed,packed:state.packed,repaired:state.repaired,sensor:state.sensor,meal:{food:state.food,drink:state.drink,filling:state.filling,served:state.servedMeal},route:state.route});
window.advanceTime=ms=>{for(let i=0;i<Math.ceil(ms/(1000/60));i++)update(1/60);updateUI();render();};
function help(){modal('KONTROLLER','Kaptenens handbok','Gå: pilar / WASD. Dra i bilden: titta och sikta. J/L: vrid kameran. E: använd närmaste sak. Siktet i mitten visar var du siktar. Mellanslag/Q eller Slå: ta nytt vapen vid hållaren, öppna/gå genom raketdörr, prata nära kompis; annars använd aktuellt vapen. R eller Hoppa: hoppa. 1: pistol, 2: svärd (efter att du hämtat vapen). F: helskärm. På pekskärm: dra styrspaken för att gå, dra i spelbilden för att sikta och använd Slå/Hoppa samtidigt. Stationens karta går genom gångarna. I raketen: gå till trapporna och använd dem. Mittenrummet har karta och hjälpdator; cockpit kör; nedersta våningen har utgång. Kartlägg alla fem främmande planeter. Främmande planeter går runt i båda riktningarna. Hitta raketen pekar mot landningsplatsen. Från rymden: Res till planet. Fiendeskeppets öppna dockning kan nås med rörelse, hopp eller Slå. Nära markerad vägg/tunna ombord tar Slå skydd; I skydd: Slå kikar upp och skjuter; då är du träffbar. Utan skjutning är du gömd och kan inte träffas. Rörelse, Hoppa eller Lämna skydd lämnar det. Vid noll liv räddas du till stationen. Mat ger sex liv.',[['Fortsätt',()=>{}]]);}
async function fullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else await $('#game').requestFullscreen();}catch{notify('Helskärm är inte tillgänglig i denna webbläsare.');}}
$('#start').onclick=()=>{state.started=true;$('#welcome').hidden=true;notify('Välkommen, kapten! Prata med kompisarna eller öppna stationens karta.');updateUI();};$('#help').onclick=help;$('#fullscreen').onclick=fullscreen;$('#weapon').onclick=()=>{const w=state.player.weapon==='pistol'?'sword':'pistol';if(state.player.inventory.includes(w))equip(w);else notify('Hämta vapnet i träningsrummet först.');};
window.addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space','KeyQ'].includes(e.code))e.preventDefault();if(e.repeat){if(!state.dialog&&!['Space','KeyQ'].includes(e.code))keys.add(e.code);return;}if(e.code==='KeyE')use();if(e.code==='KeyR')jump();if((e.code==='Space'||e.code==='KeyQ')&&contextAction())return;if(e.code==='KeyF')fullscreen();if(e.code==='Escape')closeModal();if(e.code==='Digit1'&&state.player.inventory.includes('pistol'))equip('pistol');if(e.code==='Digit2'&&state.player.inventory.includes('sword'))equip('sword');if(!state.dialog)keys.add(e.code);});window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>{keys.clear();stopStick();look=null;});document.addEventListener('visibilitychange',()=>{if(document.hidden){keys.clear();stopStick();look=null;}});
for(const b of document.querySelectorAll('[data-key]')){b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);if(b.dataset.key==='KeyR')jump();else{if(b.dataset.key==='Space'&&contextAction())return;if(!state.dialog)keys.add(b.dataset.key);}});for(const t of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(t,()=>keys.delete(b.dataset.key));}
const joystick=$('#joystick'),thumb=$('#stick-thumb');
function stopStick(){const id=stick.id;stick.id=null;stick.x=stick.y=0;thumb.style.transform='translate(0px,0px)';joystick.classList.remove('active');if(id!==null&&joystick.hasPointerCapture(id))joystick.releasePointerCapture(id);}
function moveStick(e){const r=joystick.getBoundingClientRect(),radius=(r.width-40)/2-4;let x=(e.clientX-r.left-r.width/2)/radius,y=(e.clientY-r.top-r.height/2)/radius;const len=Math.hypot(x,y);if(len>1){x/=len;y/=len;}thumb.style.transform=`translate(${x*radius}px,${y*radius}px)`;const magnitude=Math.hypot(x,y),speed=Math.max(0,(magnitude-.15)/.85);stick.x=magnitude?x/magnitude*speed:0;stick.y=magnitude?y/magnitude*speed:0;}
joystick.addEventListener('pointerdown',e=>{e.preventDefault();e.stopPropagation();if(!state.started||state.dialog||stick.id!==null)return;stick.id=e.pointerId;joystick.setPointerCapture(e.pointerId);joystick.classList.add('active');moveStick(e);});joystick.addEventListener('pointermove',e=>{if(e.pointerId!==stick.id)return;e.preventDefault();e.stopPropagation();moveStick(e);});for(const evt of ['pointerup','pointercancel','lostpointercapture'])joystick.addEventListener(evt,e=>{if(e.pointerId===stick.id)stopStick();});
let look=null;
canvas.addEventListener('pointerdown',e=>{if(!state.started||state.dialog||look)return;e.preventDefault();look={id:e.pointerId,x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);});
canvas.addEventListener('pointermove',e=>{if(!look||look.id!==e.pointerId)return;state.player.aim+=(e.clientX-look.x)*.0045;state.player.pitch=Math.max(-1.15,Math.min(1.15,state.player.pitch-(e.clientY-look.y)*.004));look.x=e.clientX;look.y=e.clientY;render();});
for(const evt of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(evt,e=>{if(look?.id===e.pointerId)look=null;});
window.addEventListener('resize',()=>view.resize());
let previous=performance.now();function frame(t){update(Math.min(.035,(t-previous)/1000));previous=t;updateUI();render();requestAnimationFrame(frame);}requestAnimationFrame(frame);updateUI();render();
