import {THREE,M,mat,box,sphere,animateMonster} from './models.js?v=20261009-1';
import {SUBJECTS,STORY,correct} from './curriculum.js?v=20261009-1';
import {createWorld,addPiece,inRect,zoneAt} from './world.js?v=20261009-1';

const $=id=>document.getElementById(id), clamp=THREE.MathUtils.clamp, dist=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z);
const VERSION='20261009-1', SPEED=3.4, SLOW_TIME=3, WATER_STOP=5, SLIDE_SPEED=10;
const coarse=matchMedia('(pointer:coarse)').matches||navigator.maxTouchPoints>0;
let renderer;
try{renderer=new THREE.WebGLRenderer({canvas:$('game'),antialias:true,powerPreference:'high-performance',preserveDrawingBuffer:!!navigator.webdriver})}catch(e){$('loadError').hidden=false;throw e}
renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;renderer.setPixelRatio(Math.min(devicePixelRatio||1,coarse?1.25:1.6));
const scene=new THREE.Scene();scene.background=new THREE.Color(0x6a8589);scene.fog=new THREE.Fog(0x6a8589,85,240);
scene.add(new THREE.HemisphereLight(0xe4f2e5,0x546456,2.1));scene.add(new THREE.AmbientLight(0xffe8c3,.7));const sun=new THREE.DirectionalLight(0xffe4b5,2.3);sun.position.set(-30,60,35);scene.add(sun);
const camera=new THREE.PerspectiveCamera(73,1,.06,350);camera.rotation.order='YXZ';scene.add(camera);
const arm=new THREE.Group();camera.add(arm);box(arm,.2,.22,.65,.4,-.36,-.62,M.navy);sphere(arm,.14,.4,-.4,-.94,M.skin);const heldBall=sphere(arm,.23,.38,-.34,-.97,M.orange);const heldWater=box(arm,.32,.5,.3,.4,-.25,-.95,M.blue);arm.visible=false;
const w=createWorld(scene);const keys=new Set(),held=new Set();let joystick={x:0,y:0},stickId=null,lookId=null,lookAt={x:0,y:0},lastNow=performance.now(),manual=false,audioCtx=null;
const fresh=()=>({mode:'menu',time:0,player:{x:-15,y:0,z:40,yaw:0,pitch:0,vy:0,grounded:true,support:null},done:{},answers:Object.fromEntries(SUBJECTS.filter(s=>s.answers).map(s=>[s.id,s.answers.map(()=> '')])),book:false,ball:null,water:false,safeDiscovered:false,board:null,message:'',messageUntil:0,immuneUntil:0,boostUntil:0,ride:null,build:false,carrying:null,rotated:false,gym:{phase:'balls',hits:0,timer:0,route:false,visited:[],started:false},football:{active:false,player:0,snabbis:0,reset:0,ball:{x:25,z:117,vx:0,vz:0}},escape:'locked',driveTime:0,jumpTime:0,endingTime:0,catches:0,projectiles:[],monsters:{enogat:{x:0,z:-28,target:1,slowUntil:0,lostUntil:0},snabbis:{x:32,z:62,target:0,slowUntil:0,lostUntil:0},spider:{x:34,z:-27,target:0,slowUntil:0,lostUntil:0},mouth:{x:8,z:-75,target:0,slowUntil:0,lostUntil:0}}});
let s=fresh();
function tone(f=300,len=.09){try{audioCtx??=new(window.AudioContext||window.webkitAudioContext)();audioCtx.resume();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sine';o.frequency.setValueAtTime(f,audioCtx.currentTime);o.frequency.exponentialRampToValueAtTime(f*.55,audioCtx.currentTime+len);g.gain.setValueAtTime(.035,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+len);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+len)}catch{}}
function say(text,seconds=4){s.message=text;s.messageUntil=s.time+seconds;$('notice').textContent=text}
function resetInput(){keys.clear();held.clear();joystick={x:0,y:0};stickId=null;lookId=null;$('knob').style.transform='';document.querySelectorAll('[data-action]').forEach(b=>b.classList.remove('active'))}
function start(){resetInput();s=fresh();s.mode='playing';w.gate.enabled=true;w.gate.mesh.visible=true;w.truck.position.set(0,0,-128);w.truck.rotation.set(0,0,0);w.actor.visible=false;w.monsters.mouth.userData.apron.visible=true;w.monsters.mouth.userData.tray.visible=true;w.leafpile.position.set(-12,0,-181);for(const p of w.pieces){w.root.remove(p.mesh);p.mesh.geometry.dispose()}w.pieces=[];for(let i=0;i<7;i++)addPiece(w,'cube',20+i%4*2.6,-17-Math.floor(i/4)*3,0,i%2===0);for(let i=0;i<3;i++)addPiece(w,'mat',29+i*4,-36,0,i===1);for(const id of ['menu','helpScreen','pauseScreen','mapScreen','boardScreen','endingScreen'])$(id).hidden=true;syncUI();tone(420);$('game').focus();render()}
function allDone(){return SUBJECTS.every(q=>s.done[q.id])}
function zone(){return zoneAt(s.player.x,s.player.z)}
const names={math:'Matterummet',swedish:'Svenskarummet',english:'Engelskarummet',social:'SO-rummet',science:'NO-rummet',gym:'Idrottssalen',corridor:'Korridoren',yard:'Skolgården',dining:'Matsalen',kitchen:'Köket',loading:'Lastkajen',forest:'Vid skogen'};
function objective(){if(s.escape==='truck')return 'Du är skyddad i lastutrymmet. Vrid nyckeln.';if(s.escape==='driving')return s.driveTime<3?'Motorn går. Munvrålet klättrar upp på taket…':'En lövhög vid skogen! Tryck HOPPA UT.';if(s.escape==='landed')return 'Du landade mjukt. Spring in bland träden.';if(['dining','kitchen','loading'].includes(zone())&&allDone())return 'Hitta vatten. Följ köket rakt fram till lastkajen.';if(s.football.active)return `Fotboll · du ${s.football.player} – ${s.football.snabbis} Snabbis · först till 3`;if(zone()==='gym'){const g=s.gym;return g.phase==='balls'?`1. Träffa Åttaben med boll · ${g.hits}/10`:g.phase==='build'?`2. Golvet är Åttaben · ${g.route?'bygg en väg till den gula målplatsen':'hoppa upp på blå startplatsen'}`:g.phase==='count'?`3. Göm dig! Åttaben räknar · ${Math.ceil(g.timer)} s`:g.phase==='seek'?`Åttaben letar · ${Math.ceil(g.timer)} s kvar`:'Idrotten är klar. Du kan fortsätta leka.'}if(allDone())return 'Sex ämnen klara! Fly genom matsalen längst bort i korridoren.';if(zone()==='yard')return s.ball?'Lek på gården. Fotboll är frivilligt.':'Lek på gården. Bollar finns i förrådet.';return 'Klara skolans sex ämnen. Hitta tavlorna och idrottssalen.'}
function syncUI(){const playing=s.mode==='playing';for(const id of ['hud','crosshair','touch','topButtons','prompt'])$(id).hidden=!playing;arm.visible=playing;heldBall.visible=s.ball!==null&&!s.water;heldWater.visible=s.water;$('subjects').innerHTML=SUBJECTS.map(q=>`<span class="${s.done[q.id]?'done':''}">${q.short}${s.done[q.id]?' ✓':''}</span>`).join('');$('zoneLabel').textContent=names[zone()]||'Skolan';$('objective').textContent=objective();$('notice').textContent=s.time<s.messageUntil?s.message:'';$('buildTools').hidden=!s.build||!playing;$('buildButton').disabled=zone()!=='gym';$('throwButton').disabled=!s.ball&&!s.water;$('throwButton').textContent=s.water?'VATTEN':s.football.active?'SKJUT':'KASTA';$('useButton').textContent=s.ride?'KLIV AV':s.escape==='truck'?'NYCKEL':s.escape==='driving'?'HOPPA UT':'TA SAK';$('buildLabel').textContent=s.carrying?`Bär ${s.carrying.type==='cube'?'kub':'matta'} · sikta, placera eller vrid`:'Ta en kub eller matta. Du kan flytta det du byggt.'}
function openBoard(id){if(id==='swedish'&&!s.book){say('Ta sagoboken på bordet först. Sedan kan du hålla den medan du skriver.');return}resetInput();s.board=id;s.mode='board';const sub=SUBJECTS.find(q=>q.id===id);$('boardTitle').textContent=sub.name;$('bookPage').hidden=id!=='swedish';$('storyText').textContent=STORY;$('boardFields').replaceChildren();sub.questions.forEach((q,i)=>{const row=document.createElement('div');row.className='answer-row';row.dataset.index=i;const label=document.createElement('label');label.htmlFor='answer-'+i;label.textContent=q;const line=document.createElement('div');line.className='input-line';const input=document.createElement(id==='swedish'?'textarea':'input');input.id='answer-'+i;input.value=s.answers[id][i];input.autocomplete='off';input.spellcheck=false;input.addEventListener('focus',()=>requestAnimationFrame(()=>input.scrollIntoView({block:'nearest',inline:'nearest'})));input.setAttribute('autocapitalize','off');input.setAttribute('aria-label',q);if(id==='math'){input.inputMode='numeric';input.pattern='[0-9]*'}input.addEventListener('input',()=>{s.answers[id][i]=input.value;if(!input.composing)checkBoard()});input.addEventListener('compositionstart',()=>input.composing=true);input.addEventListener('compositionend',()=>{input.composing=false;s.answers[id][i]=input.value;checkBoard()});const erase=document.createElement('button');erase.type='button';erase.textContent='SUDDA';erase.setAttribute('aria-label','Sudda svar '+(i+1));erase.addEventListener('click',()=>{const a=input.selectionStart,b=input.selectionEnd;if(a!==b){input.setRangeText('',a,b,'start')}else{input.value=''}s.answers[id][i]=input.value;checkBoard();input.focus()});line.append(input,erase);row.append(label,line);$('boardFields').append(row)});$('boardScreen').hidden=false;checkBoard();syncUI()}
function checkBoard(){const sub=SUBJECTS.find(q=>q.id===s.board);let count=0;sub.answers.forEach((_,i)=>{const ok=correct(sub.id,i,s.answers[sub.id][i]);count+=+ok;$('boardFields').children[i].classList.toggle('correct',ok)});s.done[sub.id]=count===sub.answers.length;$('boardProgress').textContent=s.done[sub.id]?'ÄMNET KLART ✓':`${count} av ${sub.answers.length} klara`;checkProgress()}
function checkProgress(){if(allDone()&&s.escape==='locked'){s.escape='ready';w.gate.enabled=false;w.gate.mesh.visible=false}if(!allDone()&&s.escape==='ready'){s.escape='locked';w.gate.enabled=true;w.gate.mesh.visible=true}}
function closeBoard(){s.board=null;s.mode='playing';$('boardScreen').hidden=true;resetInput();syncUI();$('game').focus()}
function isWalkable(x,z){const zz=zoneAt(x,z);if(zz==='outside')return false;if(zz==='forest')return s.escape==='landed'||s.mode==='ending'||s.mode==='won';return true}
function obstacle(x,z,y,r=.43,monster=false){if(!isWalkable(x,z))return true;for(const c of w.walls)if(c.enabled&&y+(monster?1.7:1.62)>c.minY&&y<c.maxY-.08&&Math.abs(x-c.x)<c.w/2+r&&Math.abs(z-c.z)<c.d/2+r)return true;for(const c of w.pieces)if(y+1.62>c.bottom&&y<c.bottom+c.h-.08&&Math.abs(x-c.x)<c.w/2+r&&Math.abs(z-c.z)<c.d/2+r)return true;return false}
function terrain(x,z){const h=w.hill,d=Math.hypot(x-h.x,z-h.z);return d<h.r?h.h*(1-d/h.r):0}
function surface(x,z,maxY=100){let best={y:terrain(x,z),id:'floor'};for(const q of w.surfaces)if(inRect(x,z,q)&&q.y<=maxY&&q.y>best.y)best={y:q.y,id:q.id};for(const q of w.pieces)if(inRect(x,z,q)&&q.bottom+q.h<=maxY&&q.bottom+q.h>best.y)best={y:q.bottom+q.h,id:q.id};return best}
function lineClear(a,b,height=1.2){const n=Math.ceil(dist(a,b)*2);for(let i=1;i<n;i++){const t=i/n,x=a.x+(b.x-a.x)*t,z=a.z+(b.z-a.z)*t;if(w.walls.some(c=>c.enabled&&height>c.minY&&height<c.maxY&&Math.abs(x-c.x)<c.w/2&&Math.abs(z-c.z)<c.d/2)||w.pieces.some(c=>height>c.bottom&&height<c.bottom+c.h&&inRect(x,z,c)))return false}return true}
function movePlayer(dt){const p=s.player;if(s.ride){updateRide(dt);return}if(['truck','driving','jumping'].includes(s.escape)){updateTruck(dt);return}let ix=+(keys.has('KeyD')||keys.has('ArrowRight'))-+(keys.has('KeyA')||keys.has('ArrowLeft'))+joystick.x,iz=+(keys.has('KeyS')||keys.has('ArrowDown'))-+(keys.has('KeyW')||keys.has('ArrowUp'))+joystick.y;const len=Math.hypot(ix,iz);if(len>1){ix/=len;iz/=len}const running=held.has('sprint')||keys.has('ShiftLeft')||keys.has('ShiftRight');const duck=held.has('crouch')||keys.has('KeyC');const speed=(running?7.5:4.7)*(s.time<s.boostUntil?1.42:1)*(duck?.55:1);const dx=(Math.cos(p.yaw)*ix+Math.sin(p.yaw)*iz)*speed*dt,dz=(-Math.sin(p.yaw)*ix+Math.cos(p.yaw)*iz)*speed*dt;const step=(x,z)=>{let yy=p.y;const surf=surface(x,z,p.y+.4);if(p.grounded&&surf.y<=p.y+.4&&surf.y>p.y)yy=surf.y;if(!obstacle(x,z,yy)){p.x=x;p.z=z;p.y=yy}};step(p.x+dx,p.z);step(p.x,p.z+dz);const oldY=p.y;p.vy-=19*dt;p.y+=p.vy*dt;const surf=surface(p.x,p.z,Math.max(oldY,p.y)+.05);if(p.y<=surf.y&&p.vy<=0){p.y=surf.y;p.vy=0;p.grounded=true;p.support=surf.id}else{p.grounded=false;p.support=null}if(p.y<-.5){p.y=0;p.vy=0}if(zone()==='math'&&!s.safeDiscovered&&s.time>3){s.safeDiscovered=true;say('Det är alldeles lugnt här inne. Bord och stolar står kvar.',5)}if(s.escape==='landed'&&p.x<-23&&p.z<-143)beginEnding();}
function jump(){if(s.mode!=='playing')return;if(s.ride){dismount();return}if(s.escape==='driving'){truckJump();return}if(s.player.grounded&&s.escape!=='truck'){s.player.vy=8.65;s.player.grounded=false;tone(170,.07)}}
function nearest(){const p=s.player;return w.interacts.filter(q=>Math.hypot(p.x-q.x,p.z-q.z)<(q.radius||3.5)&&Math.abs(p.y-q.y)<3.5&&lineClear(p,q,1.3)).sort((a,b)=>dist(p,a)-dist(p,b))[0]}
function use(){if(s.mode!=='playing')return;if(s.ride){dismount();return}if(s.escape==='truck'){s.escape='driving';s.driveTime=0;s.player.yaw=Math.PI;s.player.pitch=0;say('Motorn startar. Munvrålet hoppar upp på taket!',4);tone(75,.4);return}if(s.escape==='driving'){truckJump();return}const q=nearest();if(!q){say('Gå närmare saken du vill använda.',2);return}if(q.subject){openBoard(q.subject);return}const p=s.player;
 switch(q.id){case 'book':s.book=true;say('Du håller sagoboken. Den följer med till tavlan.');tone(500);break;
 case 'dining':if(!allDone())say(`Klara alla sex ämnen först · ${SUBJECTS.filter(x=>s.done[x.id]).length}/6.`);else say('Dörren till matsalen är öppen.');break;
 case 'gymBalls':s.ball='gym';s.water=false;say('Du har oändligt med bollar. Sikta mot Åttaben och kasta.');break;
 case 'yardBalls':s.ball='yard';s.water=false;say('Du har oändligt med fotbollar. Ta med dem överallt på gården.');break;
 case 'buildSupply':toggleBuild(true);break;
 case 'climber':p.x=14;p.z=78;p.y=3.95;p.vy=0;p.grounded=true;say('Uppe i klätterställningen. Du kan gå, hoppa och klättra ner.');break;
 case 'houseRoof':p.x=-40;p.z=113;p.y=3.8;p.vy=0;p.grounded=true;s.monsters.snabbis.lostUntil=s.time+10;say('Snabbis tappar bort dig här uppe.');break;
 case 'water':s.water=true;s.ball=null;say('Oändligt vatten! Sikta på den lysande munnen och kasta.');tone(600);break;
 case 'truck':if(!allDone())return;s.escape='truck';p.x=0;p.z=-125;p.y=1.3;p.yaw=0;p.pitch=0;say('Du är säker här. Vrid nyckeln för att starta motorn.');break;
 case 'football':if(!s.ball){say('Hämta en fotboll i förrådet först.');break}startFootball();break;
 default:if(q.id.startsWith('swing')){const a=w.swings.find(a=>a.id===q.id);s.ride={type:'swing',id:a.id,time:0};s.monsters.snabbis.lostUntil=s.time+9;say(a.big?'Gunga! Kompisgungan kan bromsa Snabbis.':'Snabbis kan inte nå dig på gungan.')}else if(q.id.startsWith('slide')){const a=w.slides.find(a=>a.id===q.id);s.ride={type:'slide',id:a.id,time:0};p.x=a.x;p.y=a.h;p.z=a.z;say('Susar ner! Snabbis måste springa runt.')}else if(q.id.startsWith('spin')){s.ride={type:'spin',id:q.id,time:0};say('Snurra när Snabbis är nära!')}
 }syncUI();}
function updateRide(dt){const r=s.ride,p=s.player;r.time+=dt;if(r.type==='swing'){const a=w.swings.find(x=>x.id===r.id);const angle=Math.sin(r.time*2.3)*.88;a.pivot.rotation.x=angle;p.x=a.x;p.y=a.height-Math.cos(angle)*a.len+.35;p.z=a.z+Math.sin(angle)*a.len+.6;s.monsters.snabbis.lostUntil=s.time+5;if(a.big&&dist(s.monsters.snabbis,a)<6&&Math.abs(angle)>.45)slow('snabbis');}else if(r.type==='slide'){const a=w.slides.find(x=>x.id===r.id),t=Math.min(1,r.time*SLIDE_SPEED/Math.hypot(a.len,a.h));p.x=a.x;p.z=a.z-a.len*t;p.y=a.h*(1-t);p.yaw=0;p.pitch=-.1;if(t===1){s.monsters.snabbis.lostUntil=s.time+7;s.ride=null;p.y=terrain(p.x,p.z);p.vy=0;p.grounded=true;say('Du är på andra sidan. Snabbis letar vid starten.',3)}}else{const a=w.spinners.find(x=>x.id===r.id);a.group.rotation.y+=dt*7;p.x=a.x;p.z=a.z;p.y=.8;p.yaw+=dt*1.7;if(dist(s.monsters.snabbis,a)<9&&!s.monsters.snabbis.fling){const m=s.monsters.snabbis;m.fling={x:m.x,z:m.z,time:0};m.lostUntil=s.time+12;slow('snabbis');say('Snabbis flög till lilla rutschkanan och tappade bort dig!')}}}
function dismount(){const r=s.ride;if(!r)return;const a=r.type==='swing'?w.swings.find(a=>a.id===r.id):r.type==='spin'?w.spinners.find(a=>a.id===r.id):w.slides.find(a=>a.id===r.id);s.player.x=a.x+3.6;s.player.z=a.z+3;s.player.y=terrain(s.player.x,s.player.z);s.player.vy=0;s.player.grounded=true;s.ride=null;syncUI()}
function slow(id){s.monsters[id].slowUntil=s.time+SLOW_TIME;tone(160,.1)}
function toggleBuild(force){if(zone()!=='gym'){say('Kuberna och mattorna finns i idrottssalen.');return}s.build=force??!s.build;if(!s.build&&w.ghost)w.ghost.visible=false;syncUI()}
function placement(){const p=s.player,type=s.carrying?.type||'cube',width=type==='mat'&&!s.rotated?4.8:2.4,depth=type==='mat'&&s.rotated?4.8:2.4;const x=Math.round((p.x-Math.sin(p.yaw)*4)/1.2)*1.2,z=Math.round((p.z-Math.cos(p.yaw)*4)/1.2)*1.2;let bottom=0;for(const q of [...w.surfaces.map(a=>({...a,bottom:0,h:a.y})),...w.pieces])if(Math.abs(x-q.x)<(width+q.w)/2-.1&&Math.abs(z-q.z)<(depth+q.d)/2-.1)bottom=Math.max(bottom,q.bottom+q.h);return {x,z,bottom,w:width,d:depth,h:type==='cube'?1.8:.3,type}}
function validPlacement(q){return q.x-q.w/2>5.5&&q.x+q.w/2<44.5&&q.z-q.d/2>-49.5&&q.z+q.d/2<-10.5&&q.bottom+q.h<7.3&&!(Math.abs(s.player.x-q.x)<q.w/2+.45&&Math.abs(s.player.z-q.z)<q.d/2+.45&&s.player.y<q.bottom+q.h)&&!w.walls.some(c=>c.enabled&&c.maxY>q.bottom+.1&&c.minY<q.bottom+q.h-.1&&Math.abs(q.x-c.x)<(q.w+c.w)/2-.1&&Math.abs(q.z-c.z)<(q.d+c.d)/2-.1)}
function buildAction(action){if(zone()!=='gym')return;if(action==='close'){s.build=false;s.carrying=null}else if(action==='cube'||action==='mat'){s.carrying={type:action};s.rotated=false}else if(action==='rotate'){s.rotated=!s.rotated}else if(action==='pickup'){const p=s.player,candidates=w.pieces.filter(q=>dist(p,q)<6).sort((a,b)=>dist(p,a)-dist(p,b));const q=candidates[0];if(q){if(w.pieces.some(a=>a!==q&&Math.abs(a.bottom-(q.bottom+q.h))<.1&&Math.abs(a.x-q.x)<(a.w+q.w)/2&&Math.abs(a.z-q.z)<(a.d+q.d)/2)){say('Flytta den översta delen först.');return}s.carrying={type:q.type};s.rotated=q.rotated;w.root.remove(q.mesh);q.mesh.geometry.dispose();w.pieces.splice(w.pieces.indexOf(q),1);say('Du lyfte upp den. Välj en ny plats.',2)}else say('Gå nära kuben eller mattan du vill flytta.')}else if(action==='place'&&s.carrying){const q=placement();if(!validPlacement(q)){say('Det är för trångt här. Sikta mot en fri plats.',2);return}addPiece(w,q.type,q.x,q.z,q.bottom,s.rotated);tone(210);say('Placerad. Du kan bygga vidare eller flytta den igen.',2)}syncUI()}
function updateGhost(){if(!s.build||!s.carrying){if(w.ghost)w.ghost.visible=false;return}const q=placement();if(!w.ghost){w.ghost=box(w.root,1,1,1,0,0,0,mat(0x91f4ce,{transparent:true,opacity:.43,depthWrite:false}));}w.ghost.visible=true;w.ghost.scale.set(q.w,q.h,q.d);w.ghost.position.set(q.x,q.bottom+q.h/2,q.z);w.ghost.material.color.set(validPlacement(q)?0x91f4ce:0xec6d67)}
const matchBall=sphere(w.root,.38,25,.38,117,M.light);matchBall.visible=false;
function startFootball(){if(s.football.active)return;s.football={active:true,player:0,snabbis:0,reset:0,ball:{x:25,z:117,vx:0,vz:0}};resetPitch();say('Du gör mål i bortre målet. Spring till bollen och skjut! Först till tre.',6)}
function resetPitch(){s.player.x=25;s.player.z=127;s.player.y=0;s.player.yaw=0;s.player.pitch=0;s.monsters.snabbis.x=25;s.monsters.snabbis.z=107;Object.assign(s.football.ball,{x:25,z:117,vx:0,vz:0});s.football.reset=1.3}
function finishFootball(won){s.football.active=false;matchBall.visible=false;s.monsters.snabbis.lostUntil=s.time+8;if(won){s.boostUntil=s.time+15;say('Du vann! Extra fart i 15 sekunder.',5);tone(700,.2)}else say('Snabbis vann. Du kan spela igen när du vill.',4)}
function updateFootball(dt){const f=s.football;if(!f.active){matchBall.visible=false;return}matchBall.visible=true;const b=f.ball,m=s.monsters.snabbis,p=s.player;if(p.x<8||p.x>42||p.z<100||p.z>134){f.active=false;say('Du lämnade matchen. Den är frivillig.');return}f.reset=Math.max(0,f.reset-dt);if(f.reset===0){if(dist(p,b)<.9){b.vx=-Math.sin(p.yaw)*5;b.vz=-Math.cos(p.yaw)*5}const d=dist(m,b);if(d>1){m.x+=(b.x-m.x)/d*3.5*dt;m.z+=(b.z-m.z)/d*3.5*dt}else{const tx=25-m.x,tz=132-m.z,n=Math.hypot(tx,tz);b.vx=tx/n*10;b.vz=tz/n*10}b.x+=b.vx*dt;b.z+=b.vz*dt;const friction=Math.exp(-.48*dt);b.vx*=friction;b.vz*=friction;if(b.x<10.4||b.x>39.6){b.x=clamp(b.x,10.4,39.6);b.vx*=-.7}if(b.z<102.8||b.z>131.2){if(b.x>21&&b.x<29){if(b.z<117)f.player++;else f.snabbis++;tone(650,.13);if(f.player===3||f.snabbis===3){finishFootball(f.player===3);return}say(`Mål! Du ${f.player} – ${f.snabbis} Snabbis`,3);resetPitch()}else{b.z=clamp(b.z,102.8,131.2);b.vz*=-.75}}}matchBall.position.set(b.x,.44,b.z);matchBall.rotation.x+=Math.hypot(b.vx,b.vz)*dt;w.monsters.snabbis.position.set(m.x,terrain(m.x,m.z),m.z);w.monsters.snabbis.rotation.y=Math.atan2(b.x-m.x,b.z-m.z);animateMonster(w.monsters.snabbis,s.time,f.reset===0)}
function throwItem(){if(s.mode!=='playing'||s.time<(s.throwAfter||0))return;s.throwAfter=s.time+.38;const p=s.player;if(s.football.active){const b=s.football.ball;if(dist(p,b)>3){say('Gå närmare bollen för att skjuta.',2);return}b.vx=-Math.sin(p.yaw)*19;b.vz=-Math.cos(p.yaw)*19;tone(220);return}if(!s.water&&!s.ball){say('Hämta en boll först.',2);return}const water=s.water,id=water?'mouth':zone()==='gym'?'spider':'snabbis',m=s.monsters[id];const targetY=water?4.73:id==='spider'?1.4:1.9,dx=m.x-p.x,dz=m.z-p.z,d=Math.hypot(dx,dz),dot=(-Math.sin(p.yaw)*dx-Math.cos(p.yaw)*dz)/(d||1),aim=dot>.78&&d<23&&lineClear(p,m,1.25);const startY=p.y+1.45;const direction=new THREE.Vector3(aim?dx:-Math.sin(p.yaw)*18,aim?targetY-startY:Math.sin(p.pitch)*18,aim?dz:-Math.cos(p.yaw)*18).normalize();const mesh=sphere(w.root,water?.17:.3,p.x,startY,p.z,water?M.sky:M.orange);s.projectiles.push({mesh,x:p.x,y:startY,z:p.z,vx:direction.x*24,vy:direction.y*24,vz:direction.z*24,water,target:id,life:2,aim});tone(water?650:260,.08)}
function updateProjectiles(dt){for(const a of [...s.projectiles]){a.life-=dt;a.x+=a.vx*dt;a.y+=a.vy*dt;a.z+=a.vz*dt;if(!a.aim)a.vy-=8*dt;a.mesh.position.set(a.x,a.y,a.z);const m=s.monsters[a.target],targetY=a.water?4.73:a.target==='spider'?1.4:1.9;if(Math.hypot(a.x-m.x,a.z-m.z)<1.5&&Math.abs(a.y-targetY)<1.2){if(a.water){m.slowUntil=s.time+WATER_STOP;say('Vatten i munnen! Munvrålet stannar i fem sekunder.',2)}else{slow(a.target);if(a.target==='spider'&&s.gym.phase==='balls'){s.gym.hits++;if(s.gym.hits>=10){s.gym.phase='build';say('Tio träffar! Nu: Golvet är Åttaben. Bygg från blå startplats till gul målplats.',6)}else say(`${s.gym.hits} av 10 bollträffar`,1.2)}}a.life=0}if(a.y<0||w.walls.some(c=>c.enabled&&a.y>c.minY&&a.y<c.maxY&&inRect(a.x,a.z,c)))a.life=0;if(a.life<=0){w.root.remove(a.mesh);a.mesh.geometry.dispose();s.projectiles.splice(s.projectiles.indexOf(a),1)}}}
function monsterMove(id,tx,tz,speed,dt,allowed){const m=s.monsters[id],dx=tx-m.x,dz=tz-m.z,d=Math.hypot(dx,dz);if(d<.15)return;const step=Math.min(speed*dt,d),angle=Math.atan2(dx,dz);for(const turn of [0,.55,-.55,1.1,-1.1,1.6,-1.6]){const x=m.x+Math.sin(angle+turn)*step,z=m.z+Math.cos(angle+turn)*step;const y=id==='snabbis'?terrain(x,z):0;if(!allowed(x,z)||obstacle(x,z,y,.65,true))continue;m.x=x;m.z=z;return}}
function caught(id){if(s.time<s.immuneUntil||s.mode!=='playing')return;s.catches++;s.immuneUntil=s.time+5;resetInput();if(id==='spider'){const g=s.gym;if(g.phase==='seek'){g.phase='count';g.timer=30;g.spotted=0;say('Åttaben hittade dig. Du får 30 nya sekunder att gömma dig.',5)}else say('Åttaben hann fram. Prova igen – bollarna tar aldrig slut.',4);Object.assign(s.player,{x:8,y:0,z:-21,vy:0,yaw:-Math.PI/2,grounded:true});g.route=false;s.monsters.spider.x=34;s.monsters.spider.z=-32;}else{Object.assign(s.player,{x:-15,y:0,z:40,vy:0,yaw:0,grounded:true});s.ride=null;say(`${id==='mouth'?'Munvrålet':id==='enogat'?'Enögat':'Snabbis'} hann ikapp. Du vaknar i matterummet. Dina svar finns kvar.`,6);if(id==='mouth'){s.monsters.mouth.x=8;s.monsters.mouth.z=-75;s.escape='ready'}}}

function canSeePlayer(a){const p=s.player,n=Math.ceil(dist(a,p)*3),endY=p.y+(held.has('crouch')||keys.has('KeyC')?.8:1.5);for(let i=1;i<n;i++){const t=i/n,x=a.x+(p.x-a.x)*t,z=a.z+(p.z-a.z)*t,y=1.55+(endY-1.55)*t;if(w.walls.some(c=>c.enabled&&y>c.minY&&y<c.maxY&&inRect(x,z,c))||w.pieces.some(c=>y>c.bottom&&y<c.bottom+c.h&&inRect(x,z,c)))return false}return true}
function updateMonsters(dt){const p=s.player,z=zone();
 const e=s.monsters.enogat;if(z==='corridor'){monsterMove('enogat',p.x,p.z,SPEED,dt,(x,z)=>Math.abs(x)<4.3&&z>-52&&z<48)}else{const target=e.target?42:-45;monsterMove('enogat',0,target,SPEED*.55,dt,(x,z)=>Math.abs(x)<4.3&&z>-52&&z<48);if(Math.abs(e.z-target)<1)e.target=1-e.target}if(z==='corridor'&&dist(p,e)<1.25)caught('enogat');
 const n=s.monsters.snabbis;if(!s.football.active&&!n.fling){const safe=!!s.ride||p.support==='houseRoof'||(Math.abs(p.x+40)<6&&Math.abs(p.z-112)<6.5&&p.y>=3.5);if(z==='yard'&&safe)n.lostUntil=Math.max(n.lostUntil,s.time+5);const chasing=z==='yard'&&!safe&&s.time>n.lostUntil&&dist(p,n)<32;const points=[{x:35,z:63},{x:-22,z:95},{x:19,z:128},{x:-53,z:96}];const target=chasing?p:points[n.target%points.length];let speed=chasing?6.4:2.6;if(n.slowUntil>s.time)speed*=.24;monsterMove('snabbis',target.x,target.z,speed,dt,(x,z)=>Math.abs(x)<63&&z>52&&z<134);if(!chasing&&dist(n,target)<2)n.target++;if(chasing&&p.y-terrain(p.x,p.z)<1.35&&dist(p,n)<1.35)caught('snabbis')}
 const g=s.gym,a=s.monsters.spider;const frozen=g.phase==='count'||g.phase==='done';if(!frozen&&z==='gym'){let target=p,sp=SPEED;if(g.phase==='seek'){const visible=dist(a,p)<24&&canSeePlayer(a);g.spotted=visible?(g.spotted||0)+dt:0;if(g.spotted>.85){g.spotted=0;caught('spider')} if(!visible){const points=[{x:12,z:-18},{x:28,z:-29},{x:16,z:-43},{x:39,z:-41},{x:39,z:-18}];target=points[a.target%points.length];if(dist(a,target)<1.7)a.target++;}else target=p}if(a.slowUntil>s.time)sp*=.24;monsterMove('spider',target.x,target.z,sp,dt,(x,z)=>x>6&&x<44&&z>-49&&z<-11);if(g.phase!=='count'&&p.y<1.4&&dist(p,a)<1.6&&lineClear(a,p,.8))caught('spider')}
 const m=s.monsters.mouth,escapeZone=['dining','kitchen','loading'].includes(z);if(allDone()&&escapeZone&&!['truck','driving','jumping','landed'].includes(s.escape)){if(s.escape==='ready'){s.escape='chase';say('Servitrisen vänder sig om… Munvrålet! Det är hans händer du såg vid trädet.',6)}if(s.time>=m.slowUntil)monsterMove('mouth',p.x,p.z,4.1,dt,(x,z)=>x>-21&&x<21&&z<-54.5&&z>-132);if(dist(p,m)<1.55)caught('mouth')}
 if(n.fling){const f=n.fling;f.time+=dt;const t=Math.min(1,f.time/1.1);n.x=f.x+(-9-f.x)*t;n.z=f.z+(81-f.z)*t;n.flyY=Math.sin(t*Math.PI)*9;if(t===1){n.fling=null;n.flyY=0}}
for(const id of ['enogat','snabbis','spider','mouth']){if(id==='snabbis'&&s.football.active)continue;if(id==='mouth'&&['driving','jumping','landed'].includes(s.escape))continue;const m=s.monsters[id],model=w.monsters[id];model.position.set(m.x,id==='snabbis'?terrain(m.x,m.z)+(m.flyY||0):0,m.z);model.rotation.y=Math.atan2(p.x-m.x,p.z-m.z);animateMonster(model,s.time,(id!=='spider'||!frozen)&&s.time>=m.slowUntil);if(id==='mouth'){model.userData.apron.visible=s.escape==='ready'||s.escape==='locked';model.userData.tray.visible=model.userData.apron.visible}}
}
function updateGym(dt){if(zone()!=='gym')return;const g=s.gym,p=s.player;if(g.phase==='build'){if(p.support==='gymStart'){g.route=true;g.visited=[]}if(g.route){if(p.grounded&&p.y<1.3){g.route=false;g.visited=[];say('Börja från blå platsen igen. Bygg så att du slipper gå på golvet.',3)}if(p.support?.startsWith('piece-')&&!g.visited.includes(p.support))g.visited.push(p.support);if(p.support==='gymGoal'&&g.visited.length>=2){g.phase='count';g.timer=30;s.monsters.spider.x=12;s.monsters.spider.z=-18;say('Du byggde dig fram! Nu räknar Åttaben till 30. Göm dig!',5)}}}else if(g.phase==='count'){g.timer=Math.max(0,g.timer-dt);if(g.timer===0){g.phase='seek';g.timer=30;g.spotted=0;say('Nu kommer Åttaben! Håll dig gömd i 30 sekunder.',4)}}else if(g.phase==='seek'){g.timer=Math.max(0,g.timer-dt);if(g.timer===0){g.phase='done';s.done.gym=true;checkProgress();say('Idrott ✓',2)}}}
function truckJump(){if(s.escape!=='driving')return;if(s.driveTime<3){say('Vänta tills du ser lövhögen vid skogen.',2);return}s.escape='jumping';s.jumpTime=0;s.jumpFrom=w.truck.position.z+2;s.jumpTarget={x:-12,z:s.jumpFrom-7};w.leafpile.position.set(-12,0,s.jumpTarget.z);say('Du hoppar mot lövhögen!',2)}
function updateTruck(dt){const p=s.player;if(s.escape==='truck'){p.x=0;p.z=-126;p.y=1.3;return}if(s.escape==='driving'){s.driveTime+=dt;w.truck.position.z=-128-Math.min(s.driveTime,5)*9;p.x=0;p.z=w.truck.position.z+2;p.y=1.3;w.monsters.mouth.position.set(0,5.6*Math.sin(Math.min(1,s.driveTime/1.2)*Math.PI/2),w.truck.position.z+1+4*Math.max(0,1-s.driveTime/1.2));w.monsters.mouth.rotation.y=0;w.monsters.mouth.userData.apron.visible=false;w.monsters.mouth.userData.tray.visible=false;w.leafpile.position.z=w.truck.position.z-5;if(s.driveTime>3&&s.driveTime-dt<=3)say('En lövhög! Tryck HOPPA UT för att landa mjukt.',6)}else if(s.escape==='jumping'){s.jumpTime+=dt;const t=Math.min(1,s.jumpTime/1.25);p.x=-12*t;p.z=s.jumpFrom-7*t;p.y=1.3*(1-t)+Math.sin(t*Math.PI)*4;p.yaw=Math.PI/2;p.pitch=-.15;w.truck.position.z-=10*dt;w.monsters.mouth.position.set(0,5.6,w.truck.position.z+1);if(t===1){s.escape='landed';p.y=0;p.vy=0;p.grounded=true;say('Oskadd i en mjuk lövhög. Spring in i skogen!',5)}}}
function beginEnding(){s.mode='ending';s.endingTime=0;resetInput();s.build=false;w.actor.visible=true;$('endingScreen').hidden=false;$('endMenu').hidden=true;$('bubble').hidden=true;$('endingCaption').textContent='';w.leafpile.position.set(-12,0,-181);syncUI()}
function ending(dt){s.endingTime+=dt;const t=s.endingTime,truck=w.truck,actor=w.actor;truck.position.z=-151-t*3.1;w.monsters.mouth.position.set(0,5.6,truck.position.z+1);w.monsters.mouth.rotation.y=Math.PI;w.monsters.mouth.userData.apron.visible=false;w.monsters.mouth.userData.tray.visible=false;animateMonster(w.monsters.mouth,t,false);if(t<4){actor.position.set(0,1.35,truck.position.z+2);camera.position.set(15,9,truck.position.z+17);camera.lookAt(0,3,truck.position.z);$('endingCaption').textContent=''}else if(t<7){const u=(t-4)/3;actor.position.set(-12*u,1.3*(1-u)+Math.sin(u*Math.PI)*4,-161.4-u*19.6);actor.rotation.y=-Math.PI/2;camera.position.set(-24,7,-165);camera.lookAt(actor.position.x,2,actor.position.z)}else if(t<10){actor.position.set(-12,0,-181);camera.position.set(-22,4.5,-168);camera.lookAt(-7,2,-183);$('endingCaption').textContent='Mjukt och oskadd i lövhögen.'}else if(t<17.5){actor.position.set(-12,0,-181);camera.position.set(12,8,truck.position.z+13);camera.lookAt(0,7,truck.position.z);$('endingCaption').textContent='';$('bubble').hidden=false;$('bubble').textContent='Jag kommer ta dig någon gång. Jag kommer inte vara på taket här för evigt.'}else if(t<23){$('bubble').hidden=true;actor.position.set(-12-(t-17.5)*4,0,-181-(t-17.5)*2);actor.rotation.y=-Math.PI/2;animateMonster(actor,t,true);camera.position.set(-5,5,-169);camera.lookAt(actor.position.x,2,actor.position.z);$('endingCaption').textContent=''}else{s.mode='won';$('endingCaption').textContent='Fortsättning följer';$('endMenu').hidden=false;actor.visible=false}}
function update(dt){if(s.mode==='ending'){ending(dt);return}if(s.mode!=='playing')return;s.time+=dt;movePlayer(dt);updateMonsters(dt);updateProjectiles(dt);updateGym(dt);updateFootball(dt);if(s.escape==='landed'){w.truck.position.z-=10*dt;w.monsters.mouth.position.set(0,5.6,w.truck.position.z+1)}updateGhost();syncUI();const q=nearest();$('prompt').textContent=s.ride?'TA SAK / HOPPA · kliv av':s.escape==='truck'?'TA SAK · vrid nyckeln och starta motorn':s.escape==='driving'?(s.driveTime>=3?'HOPPA UT · mot den mjuka lövhögen':'Lastbilen kör mot skogen…'):q?`${q.name} · E / TA SAK`:''}
function render(){if(s.mode==='menu'){camera.position.set(-1,3.7,46);camera.lookAt(0,2,-34);arm.visible=false}else if(s.mode!=='ending'&&s.mode!=='won'){const p=s.player,duck=held.has('crouch')||keys.has('KeyC');camera.position.set(p.x,p.y+(duck?1:1.67),p.z);camera.rotation.set(p.pitch,p.yaw,0);arm.rotation.z=Math.sin(s.time*5)*.025;heldBall.visible=!!s.ball&&!s.water;heldWater.visible=s.water}if(s.mode==='ending'&&s.endingTime>=10&&s.endingTime<17.5)w.monsters.mouth.rotation.y=Math.atan2(camera.position.x-w.monsters.mouth.position.x,camera.position.z-w.monsters.mouth.position.z);renderer.render(scene,camera)}
function resize(){const width=$('shell').clientWidth,height=$('shell').clientHeight;renderer.setSize(width,height,false);camera.aspect=width/height;camera.updateProjectionMatrix();render()}
function pause(screen='pauseScreen'){if(s.mode!=='playing')return;resetInput();s.mode='paused';$(screen).hidden=false;if(screen==='mapScreen')$('mapProgress').textContent=SUBJECTS.map(q=>`${q.name}${s.done[q.id]?' ✓':''}`).join(' · ');syncUI()}
function resume(){s.mode='playing';$('pauseScreen').hidden=true;$('mapScreen').hidden=true;resetInput();syncUI()}
function action(name){if(name==='jump')jump();if(name==='interact')use();if(name==='throw')throwItem();if(name==='build')toggleBuild()}
async function full(){try{if(document.fullscreenElement)await document.exitFullscreen();else await $('shell').requestFullscreen()}catch{say('På iPad kan du lägga spelet på hemskärmen för större spelyta.')}}
$('start').addEventListener('click',start);$('help').addEventListener('click',()=>{$('helpScreen').hidden=false});$('helpClose').addEventListener('click',()=>{$('helpScreen').hidden=true});$('closeBoard').addEventListener('click',closeBoard);$('pauseButton').addEventListener('click',()=>pause());$('resume').addEventListener('click',resume);$('restart').addEventListener('click',start);$('mapButton').addEventListener('click',()=>pause('mapScreen'));$('mapClose').addEventListener('click',resume);$('fullscreen').addEventListener('click',full);$('endMenu').addEventListener('click',()=>{s.mode='menu';$('endingScreen').hidden=true;$('menu').hidden=false;render()});
document.querySelectorAll('[data-action]').forEach(b=>{b.addEventListener('pointerdown',e=>{if(s.mode!=='playing')return;e.preventDefault();b.setPointerCapture(e.pointerId);const a=b.dataset.action;held.add(a);b.classList.add('active');action(a)});const end=e=>{held.delete(b.dataset.action);b.classList.remove('active')};b.addEventListener('pointerup',end);b.addEventListener('pointercancel',end);b.addEventListener('lostpointercapture',end)});
document.querySelectorAll('[data-build]').forEach(b=>b.addEventListener('click',()=>buildAction(b.dataset.build)));
$('stick').addEventListener('pointerdown',e=>{if(s.mode!=='playing')return;e.preventDefault();stickId=e.pointerId;$('stick').setPointerCapture(stickId);stickMove(e)});
function stickMove(e){if(e.pointerId!==stickId)return;const r=$('stick').getBoundingClientRect(),max=r.width*.33;let x=e.clientX-r.left-r.width/2,y=e.clientY-r.top-r.height/2;const len=Math.hypot(x,y);if(len>max){x*=max/len;y*=max/len}joystick={x:x/max,y:y/max};$('knob').style.transform=`translate(${x}px,${y}px)`}
$('stick').addEventListener('pointermove',stickMove);for(const event of ['pointerup','pointercancel','lostpointercapture'])$('stick').addEventListener(event,e=>{if(e.pointerId===stickId){stickId=null;joystick={x:0,y:0};$('knob').style.transform=''}});
$('game').addEventListener('pointerdown',e=>{if(s.mode!=='playing')return;lookId=e.pointerId;lookAt={x:e.clientX,y:e.clientY};$('game').setPointerCapture(lookId)});
$('game').addEventListener('pointermove',e=>{if(e.pointerId!==lookId||s.mode!=='playing')return;const dx=e.clientX-lookAt.x,dy=e.clientY-lookAt.y;lookAt={x:e.clientX,y:e.clientY};s.player.yaw-=dx*.005;s.player.pitch=clamp(s.player.pitch-dy*.004,-1.15,1.15)});for(const event of ['pointerup','pointercancel','lostpointercapture'])$('game').addEventListener(event,e=>{if(e.pointerId===lookId)lookId=null});
window.addEventListener('keydown',e=>{if(e.target.matches('input,textarea')){if(e.code==='Escape'){e.preventDefault();closeBoard()}return}if(e.code==='KeyF'){full();return}if(e.code==='Escape'){if(s.mode==='playing')pause();else if(s.mode==='paused')resume();return}if(s.mode!=='playing')return;if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','KeyE','KeyQ','KeyB'].includes(e.code))e.preventDefault();keys.add(e.code);if(!e.repeat){if(e.code==='Space')jump();if(e.code==='KeyE')use();if(e.code==='KeyQ')throwItem();if(e.code==='KeyB')toggleBuild()}});window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>{if(s.mode==='playing')pause()});document.addEventListener('visibilitychange',()=>{if(document.hidden&&s.mode==='playing')pause()});window.addEventListener('resize',resize);window.visualViewport?.addEventListener('resize',()=>{resize();if(s.mode==='board'&&document.activeElement?.matches('input,textarea'))requestAnimationFrame(()=>document.activeElement.scrollIntoView({block:'nearest',inline:'nearest'}))});
window.render_game_to_text=()=>JSON.stringify({version:VERSION,mode:s.mode,coordinates:'x right/east, z south/toward yard, y up; player y is feet',time:+s.time.toFixed(3),zone:zone(),player:{...s.player},done:{...s.done},inventory:{book:s.book,ball:s.ball,water:s.water?'infinite':false},answers:s.answers,board:s.board,nearby:w.interacts.filter(q=>dist(s.player,q)<7).map(q=>({id:q.id,name:q.name,x:q.x,z:q.z})),objective:objective(),gym:{...s.gym},pieces:w.pieces.map(({mesh,...p})=>p),ride:s.ride,football:s.football,escape:s.escape,driveTime:s.driveTime,endingTime:s.endingTime,monsters:Object.fromEntries(Object.entries(s.monsters).map(([id,m])=>[id,{x:+m.x.toFixed(2),z:+m.z.toFixed(2),speed:id==='enogat'||id==='spider'?SPEED:id==='snabbis'?6.4:4.1,airborne:!!m.fling,slowRemaining:Math.max(0,m.slowUntil-s.time),lostRemaining:Math.max(0,m.lostUntil-s.time)}])),catches:s.catches,gateOpen:!w.gate.enabled,boostRemaining:Math.max(0,s.boostUntil-s.time),projectiles:s.projectiles.length,message:s.time<s.messageUntil?s.message:'',caption:$('endingCaption').textContent,bubble:$('bubble').hidden?'':$('bubble').textContent});
window.advanceTime=ms=>{manual=true;const steps=Math.ceil(ms/(1000/60)),dt=ms/1000/steps;for(let i=0;i<steps;i++)update(dt);render();return window.render_game_to_text()};
if(location.hostname==='127.0.0.1'||location.hostname==='localhost'||new URLSearchParams(location.search).has('qa'))window.__exit3={get state(){return s},world:w,place:(x,z,y=0,yaw=0)=>{Object.assign(s.player,{x,z,y,yaw,vy:0,pitch:0,grounded:true});syncUI();render()},use,throwItem,jump,buildAction,openBoard,checkProgress,start,keys,held,correct,STORY,update,render,manual:v=>manual=v,constants:{SPEED,SLOW_TIME,WATER_STOP,SLIDE_SPEED}};
function frame(now){const dt=Math.min((now-lastNow)/1000,.05);lastNow=now;if(!manual)update(dt);render();requestAnimationFrame(frame)}resize();syncUI();requestAnimationFrame(frame);
