import {SUBJECTS,normalize} from './curriculum.js?v=20261009-geography-3';
import {GYM,inGymHall} from './gym-layout.js?v=20261009-geography-3';
import {zoneAt} from './world.js?v=20261009-geography-3';

export const ROOM_LETTERS={math:'M',swedish:'S',english:'E',social:'SO',science:'N',gym:'I',geography:'G'};
export const MONSTER_LETTERS={snabbis:'S',enogat:'E',spider:'Å'};
const MONSTER_NAMES={snabbis:'Snabbis',enogat:'Enögat',spider:'Åttaben'};
export const MAP_VIEWS={all:[-72,-139,268,281],school:[-29,-57,59,107],gym:[23,-113,165,106],yard:[-69,47,138,91]};
export const MARK_TOLERANCE=8;
export const freshGeography=()=>({orientationStarted:false,visits:{gym:false,english:false},orientationDone:false,countries:'',countriesDone:false,monstersDone:false,survey:false,snapshot:null,pins:{},selected:'snabbis',view:'all',feedback:''});
export function correctCountries(text){return normalize(text).replace(/[\/&]/g,' ').replace(/\boch\b/g,' ').split(/\s+/).filter(Boolean).sort().join(' ')==='danmark finland norge'}
export function markerCorrect(id,g){const a=g.pins[id],b=g.snapshot?.[id];return !!a&&!!b&&Math.hypot(a.x-b.x,a.z-b.z)<=MARK_TOLERANCE&&zoneAt(a.x,a.z)===zoneAt(b.x,b.z)}

export function schoolMap({player,world,pins={},view='all',yard=true}={}){
 const bounds=yard?MAP_VIEWS[view]:[-29,-139,220,189];
 const rect=(x,z,w,d,fill,attrs='')=>`<rect x="${x-w/2}" y="${z-d/2}" width="${w}" height="${d}" fill="${fill}" stroke="#a2bfb0" stroke-width=".6" ${attrs}/>`;
 const label=(text,x,z,size=7,fill='#fff4c9')=>`<text x="${x}" y="${z}" fill="${fill}" font-size="${size}" text-anchor="middle" dominant-baseline="middle" font-weight="800">${text}</text>`;
 let out=`<svg class="school-map" viewBox="${bounds.join(' ')}" role="img" aria-label="Karta över skolan${yard?' och skolgården':''}" xmlns="http://www.w3.org/2000/svg"><rect x="-80" y="-145" width="280" height="293" fill="#16393d"/>`;
 if(yard){out+=rect(0,92.5,130,85,'#55744d','data-area="yard"')+label('SKOLGÅRD',0,60,6);for(const [x,z,w,d,name] of [[25,117,30,30,'Fotboll'],[-40,112,12,12,'Lekstuga'],[14,78,9,9,'Klätter'],[-43,68,9,8,'Gunga'],[-43,84,10,8,'Gunga']])out+=rect(x,z,w,d,'#789168')+label(name,x,z,3.5);}
 out+=rect(0,-69.5,44,31,'#465a5a')+label('MATSAL',0,-69.5,4.5)+rect(0,-98,44,26,'#465a5a')+label('KÖK',0,-98,4.5)+rect(0,-123.5,44,25,'#465a5a')+label('LASTKAJ',0,-123.5,4.5);
 out+=rect(0,-2,10,104,'#baab7c','data-area="corridor"')+rect(GYM.passage.x,GYM.passage.z,GYM.passage.w,GYM.passage.d,'#b4915e','data-area="gym-passage"');
 for(const q of SUBJECTS){const gym=q.id==='gym',w=gym?GYM.w:20,d=gym?GYM.d:20;out+=rect(q.x,q.z,w,d,gym?'#9a7748':q.id==='geography'?'#3d786e':'#32575a',`data-room="${q.id}"`);if(!gym){const dx=q.x<0?q.x+10:q.x-10;out+=`<path d="M${dx},${q.z-1.8}v3.6" stroke="#e8dbaa" stroke-width="1.4"/>`;}}
 out+=`<path d="M25,-25v8 M5,-23v4 M-4.7,50h9.4" stroke="#e8dbaa" stroke-width="1.4"/>`;
 if(world){for(const c of [...world.walls.filter(c=>c.enabled&&c.minY<1.7&&c.maxY>0),...world.pieces.filter(c=>c.bottom<1.7).map(c=>({...c}))])if(c.x>GYM.minX+.5&&c.x<GYM.maxX-.5&&c.z>GYM.minZ+.5&&c.z<GYM.maxZ-.5)out+=rect(c.x,c.z,c.w,c.d,'#b79678');}
 for(const q of SUBJECTS)out+=label(ROOM_LETTERS[q.id],q.x,q.z,q.id==='gym'?12:7);
 if(player)out+=`<circle cx="${player.x}" cy="${player.z}" r="2.1" fill="#fff" stroke="#102b31" stroke-width=".8"/><text x="${player.x+3}" y="${player.z-3}" fill="#fff" stroke="#16393d" stroke-width=".4" paint-order="stroke" font-size="4">DU</text>`;
 for(const [id,p] of Object.entries(pins))out+=`<g data-pin="${id}" pointer-events="none"><circle cx="${p.x}" cy="${p.z}" r="4.6" fill="#edafbe" stroke="#391c31" stroke-width=".8"/>${label(MONSTER_LETTERS[id],p.x,p.z,6,'#391c31')}</g>`;
 return out+'</svg>';
}
const LEGEND='Rum: M = matte · S = svenska · E = engelska · SO = samhällsorientering · N = NO · I = idrott · G = geografi';
export function createGeographyUI({state,world,resetInput,syncUI,checkProgress,say}){
 const $=id=>document.getElementById(id);let task=0;
 const progress=()=>{const g=state().geography;state().done.geography=g.orientationDone&&g.countriesDone&&g.monstersDone;checkProgress();syncUI();$('geoProgress').textContent=`${+g.orientationDone+ +g.countriesDone+ +g.monstersDone} av 3 uppgifter klara`;$('geoTasks').querySelectorAll('button').forEach(b=>b.disabled=+b.dataset.geoTask>stage())};
 const close=()=>{const s=state();s.mode='playing';s.board=null;$('geoScreen').hidden=true;$('mapScreen').hidden=true;resetInput();syncUI();$('game').focus()};
 const stage=()=>{const g=state().geography;return !g.orientationDone?0:!g.countriesDone?1:2};
 function controls(container,portable=false){const g=state().geography;
  const tools=document.createElement('div');tools.className='map-controls';
  tools.innerHTML=Object.keys(MONSTER_LETTERS).map(id=>`<button data-monster="${id}" aria-pressed="${g.selected===id}">${MONSTER_LETTERS[id]} · ${MONSTER_NAMES[id]}</button>`).join('');
  tools.querySelectorAll('[data-monster]').forEach(b=>b.onclick=()=>{g.selected=b.dataset.monster;refresh()});container.append(tools);
  const zoom=document.createElement('div');zoom.className='map-zoom';zoom.innerHTML=Object.entries({all:'HELA KARTAN',school:'SKOLAN',gym:'IDROTTSSALEN',yard:'SKOLGÅRDEN'}).map(([v,n])=>`<button data-map-view="${v}" aria-pressed="${g.view===v}">${n}</button>`).join('');zoom.querySelectorAll('button').forEach(b=>b.onclick=()=>{g.view=b.dataset.mapView;refresh()});container.append(zoom);
  const map=document.createElement('div');map.className='map-wrap';map.innerHTML=schoolMap({player:state().player,world,pins:g.pins,view:g.view});container.append(map);
  map.querySelector('svg').addEventListener('click',e=>{if(!g.survey)return;const svg=e.currentTarget,p=svg.createSVGPoint();p.x=e.clientX;p.y=e.clientY;const q=p.matrixTransform(svg.getScreenCTM().inverse());g.pins[g.selected]={x:+q.x.toFixed(2),z:+q.y.toFixed(2)};g.feedback='Markör placerad. Du kan trycka igen för att flytta den.';refresh()});
  const status=document.createElement('p');status.className='geo-feedback';status.setAttribute('role','status');status.textContent=g.feedback||'Välj en monsterbokstav. Tryck där monstret står. Förstora området för att pricka rätt.';container.append(status);
  if(g.survey){const row=document.createElement('div');row.className='geo-buttons';row.innerHTML='<button data-geo-action="scout">GÅ OCH TITTA</button><button data-geo-action="check">KONTROLLERA</button><button data-geo-action="clear">SUDDA MARKÖR</button><button data-geo-action="cancel">AVBRYT SPANING</button>';container.append(row);row.querySelector('[data-geo-action=scout]').onclick=close;row.querySelector('[data-geo-action=check]').onclick=()=>{const n=Object.keys(MONSTER_LETTERS).filter(id=>markerCorrect(id,g)).length;g.feedback=n===3?'Alla tre rätt! Geografi är klart.':`${n} av 3 rätt. Titta på monstren och flytta markörerna som behöver rättas.`;if(n===3){g.monstersDone=true;g.survey=false;say('Geografi ✓ Alla tre monster hittade på kartan.',5);progress()}refresh()};row.querySelector('[data-geo-action=clear]').onclick=()=>{delete g.pins[g.selected];g.feedback='Markören är suddad.';refresh()};row.querySelector('[data-geo-action=cancel]').onclick=()=>{g.survey=false;g.snapshot=null;g.pins={};g.feedback='';if(portable)close();else render();};}
 }
 function refresh(){if(!$('mapScreen').hidden)renderMap();else render()}
 function render(){const s=state(),g=s.geography;$('geoProgress').textContent=`${+g.orientationDone+ +g.countriesDone+ +g.monstersDone} av 3 uppgifter klara`;$('geoTasks').innerHTML=['1 · HITTA RUM','2 · SVERIGES GRANNAR','3 · MONSTERKARTAN'].map((t,i)=>`<button data-geo-task="${i}" ${i>stage()?'disabled':''} aria-pressed="${i===task}">${t}</button>`).join('');$('geoTasks').querySelectorAll('button').forEach(b=>b.onclick=()=>{task=+b.dataset.geoTask;render()});const body=$('geoBody');body.replaceChildren();
  if(task===0){body.innerHTML=`<h3>Du ska hitta I. Du ska hitta E.</h3><p>Ta med skolkartan. Gå in i båda rummen och kom tillbaka till tavlan i G.</p><div class="orientation-status"><span>I · ${g.visits.gym?'hittat ✓':'inte hittat'}</span><span>E · ${g.visits.english?'hittat ✓':'inte hittat'}</span></div><div class="map-wrap">${schoolMap({player:s.player,world,yard:false})}</div><p class="map-legend">${LEGEND}</p><button id="geoExplore">${g.orientationDone?'TILLBAKA TILL SPELET':'TA MED KARTAN'}</button>`;$('geoExplore').onclick=()=>{g.orientationStarted=true;close();say('Hitta I och E. KARTA finns uppe till höger. Kom tillbaka till G.',6)};}
  else if(task===1){body.innerHTML='<h3>Nämn Sveriges tre grannländer på kartan</h3><div class="country-layout"><img src="./assets/nordic-map.svg?v=20261009-geography-3" alt="Karta över Sverige, Norge, Finland och Danmark. Danmark ligger på andra sidan Öresund."><div><p>Danmark ligger över Öresund. Det finns ingen landgräns där.</p><label for="countryAnswer">Skriv de tre länderna i valfri ordning.</label><div class="input-line"><input id="countryAnswer" autocomplete="off" autocapitalize="off" spellcheck="false"><button id="countryErase">SUDDA</button></div><p id="countryStatus" class="geo-feedback" role="status"></p><button id="geoNext" hidden>NÄSTA UPPGIFT</button><p class="map-credit">Kartunderlag: Natural Earth</p></div></div>';
   const input=$('countryAnswer');input.value=g.countries;const change=()=>{g.countries=input.value;g.countriesDone=correctCountries(input.value);$('countryStatus').textContent=g.countriesDone?'Alla tre grannländer rätt ✓':'Skriv alla tre. Du kan rätta med pennan och suddet.';$('geoNext').hidden=!g.countriesDone;progress()};input.oninput=change;$('countryErase').onclick=()=>{const a=input.selectionStart,b=input.selectionEnd;if(a!==b)input.setRangeText('',a,b,'start');else input.value='';change();input.focus()};$('geoNext').onclick=()=>{task=2;render()};change();}
  else {body.innerHTML='<h3>Vart befinner sig de tre monstren just nu?</h3>';
   if(!g.survey&&!g.monstersDone){body.insertAdjacentHTML('beforeend','<p>Starta spaningen. Monstren står då stilla medan du går och tittar. Öppna KARTA och placera S, E och Å där de faktiskt står.</p><p>Rosa cirklar är dina monsterbokstäver. Bokstäverna inne i rummen är ämnen.</p><button id="geoSurvey">STARTA SPANING</button>');$('geoSurvey').onclick=()=>{g.snapshot=Object.fromEntries(Object.keys(MONSTER_LETTERS).map(id=>[id,{x:s.monsters[id].x,z:s.monsters[id].z}]));g.survey=true;g.pins={};g.feedback='Läget är fryst. Gå och titta eller börja markera.';g.view='all';render()};}
   else {body.insertAdjacentHTML('beforeend',`<p>${g.survey?'Spaning pågår. Monstren och spelets tid står stilla.':'Monsterkartan är klar ✓'}</p>`);controls(body);body.insertAdjacentHTML('beforeend',`<p class="map-legend">${LEGEND}</p>`);}}
 }
 function renderMap(){const s=state(),g=s.geography,body=$('mapBody');body.replaceChildren();$('mapTitle').textContent=g.survey?'Monsterkartan · läget är fryst':'Skolan och skolgården';if(g.survey){controls(body,true);body.insertAdjacentHTML('beforeend',`<p class="map-legend">${LEGEND}</p>`)}else{body.innerHTML=`<div class="map-wrap">${schoolMap({player:s.player,world})}</div><p class="map-legend">${LEGEND}</p>`;if(g.orientationStarted&&!g.orientationDone)body.insertAdjacentHTML('afterbegin',`<p class="orientation-status">Hitta I ${g.visits.gym?'✓':''} · Hitta E ${g.visits.english?'✓':''} · Sedan tillbaka till G.</p>`);}$('mapProgress').textContent=`${SUBJECTS.filter(q=>s.done[q.id]).length} av ${SUBJECTS.length} ämnen klara`}
 function open(){const g=state().geography;if(g.orientationStarted&&g.visits.gym&&g.visits.english)g.orientationDone=true;task=stage();state().board='geography';state().mode='geography';resetInput();$('geoScreen').hidden=false;progress();render()}
 function visit(){const s=state(),g=s.geography;if(!g.orientationStarted||g.orientationDone)return;for(const id of ['gym','english'])if(!g.visits[id]&&(id==='gym'?inGymHall(s.player.x,s.player.z,2):zoneAt(s.player.x,s.player.z)==='english'&&s.player.x<-7)){g.visits[id]=true;say(g.visits.gym&&g.visits.english?'Du hittade I och E! Gå tillbaka till tavlan i G.':`${ROOM_LETTERS[id]} hittat! Leta upp det andra rummet.`,5)}}
 $('geoClose').onclick=close;
 return {open,close,visit,renderMap};
}
