import {Game,VERSION} from './sim.js?v=20260923-1';
import {View} from './view.js?v=20260923-1';
const $=id=>document.getElementById(id),storage='agust-stjarnklattraren-v1';
let saved;try{saved=JSON.parse(localStorage.getItem(storage)||'null')}catch{}
const game=new Game(saved),view=new View($('game'),game),input={forward:0,side:0,attack:false},keys=new Set();
let lastMode='',lastSave='',nextSave=0,lastTime=performance.now(),manualUntil=0,joy={x:0,y:0},look=null,joyId=null,attackId=null;
function persist(force=false){if(!force&&performance.now()<nextSave)return;nextSave=performance.now()+1000;const val=JSON.stringify(game.save());if(val!==lastSave){try{localStorage.setItem(storage,val)}catch{}lastSave=val}}
function button(id,fn){$(id)?.addEventListener('click',fn)}
function resetInputs(){keys.clear();input.attack=false;joy={x:0,y:0};joyId=null;attackId=null;look=null;$('stick').style.transform='';}
function play(){game.mode='play';resetInputs();game.findContext();paint()}
function modal(){if(lastMode===game.mode)return;lastMode=game.mode;persist(true);const mode=game.mode;$('overlay').hidden=mode==='play';if(mode==='play')return;resetInputs();if(document.pointerLockElement)document.exitPointerLock();
 if(mode==='menu'){$('panel').innerHTML=`<div class="eyebrow">AGUSTS NYA ÄVENTYR</div><h1>Stjärnklättraren</h1><p>En grotta att kalla hemma.<br>Ett högt torn att utforska.<br>Oändligt med kaststjärnor.</p><button class="primary" id="start-btn">${saved?'Fortsätt äventyret':'Börja äventyret'} ✦</button><p class="small">iPad: gå med spaken, dra på bilden för att sikta.<br>Dator: WASD / piltangenter, dra för att titta. Mellanslag kastar, E använder, Shift hoppar, F helskärm.</p><p class="small">Om du dör börjar hela äventyret om.</p>`;button('start-btn',play)}
 if(mode==='pause'){$('panel').innerHTML='<h2>En liten paus</h2><p>Äventyret väntar på dig.</p><button class="primary" id="resume">Fortsätt</button><button class="secondary" id="fullscreen">Helskärm</button><p class="small">Ditt äventyr sparas på den här enheten. Döden återställer allt.</p>';button('resume',play);button('fullscreen',fullscreen)}
 if(mode==='map'){$('panel').innerHTML='<div class="eyebrow">KARTAN PÅ BERGET</div><h2>Din värld</h2><div class="mapdrawing"><div>⌂<span>Din grotta</span></div><div>♜<span>Det höga tornet</span></div></div><p>På tornets högsta våning väntar ett pris.</p><button class="primary" id="travel">Till Det höga tornet →</button><button class="secondary" id="closemap">Stäng kartan</button>';button('travel',()=>{game.travel('outside');paint()});button('closemap',play)}
 if(mode==='dead'){$('panel').innerHTML='<div class="eyebrow">ETT NYTT FÖRSÖK</div><h2>Tillbaka till grottan</h2><p>Du förlorade alla liv. Äventyret börjar om, och det du byggde är borta.</p><button class="primary" id="restart">Börja om</button>';button('restart',()=>{game.hp=50;game.lastDamage=-99;game.time=0;play()})}
 if(mode==='sleep')$('panel').innerHTML='<div class="eyebrow">I DIN EGEN GROTTA</div><h2>Du sover …</h2><p id="sleepcount">Morgon om två sekunder.</p>';
 if(mode==='reward'){$('panel').innerHTML='<div class="eyebrow">TORNET ÄR KLARAT</div><h2>Du är en stjärnklättrare!</h2><p>Du hittade klätterförmågan! Gå nära en vägg och håll inne <strong>KASTA</strong> för att klättra med kaststjärnorna. Släpp knappen för att släppa taget.</p><p>Du fick också tornets stjärna att bygga vid grottan.</p><button class="primary" id="rewardhome">Till grottan med priset</button><button class="secondary" id="stay">Stanna i tornet</button>';button('rewardhome',()=>{game.travel('home');paint()});button('stay',play)}
}
function fullscreen(){if(document.fullscreenElement)document.exitFullscreen?.();else document.documentElement.requestFullscreen?.().catch(()=>{})}
function objective(){const id=game.level.id;if(id==='home')return game.trophy?'Bygg ditt pris vid grottan':game.ability?'Håll KASTA nära en vägg för att klättra':'Kartan sitter till höger om grottöppningen';if(id==='outside')return game.keys.has('entrance')?'Lås upp dörren':'Hitta den gömda nyckeln';if(id==='floor1'||id==='floor2')return game.keys.has(id==='floor1'?'key1':'key2')?'Portalen leder tillbaka · lås upp trappan':'Utforska våningen och hitta nyckeln';return game.level.guards.some(g=>g.hp>0)?'Besegra bossen med två svärd':'Hämta förmågan på bordet'}
function paint(){modal();$('place').textContent=game.level.name;$('objective').textContent=objective();$('health').textContent=`♥ ${game.hp} / 50`;$('clock').textContent=game.dayTime<60?'☀ Dag':'☾ Natt';$('ability').textContent=game.ability?'✦ ∞ · Klättra':'✦ ∞';$('toast').textContent=game.time<game.noticeUntil?game.notice:'';$('interact').hidden=game.mode!=='play'||!game.context;if(game.context)$('interact').textContent=game.context.label;$('damage').style.opacity=game.hitFlash||0;const boss=game.level.guards.find(g=>g.boss&&g.hp>0);$('bossbar').hidden=!boss||game.mode!=='play';if(boss)$('bossbar').querySelector('progress').value=boss.hp;if(game.mode==='sleep'&&$('sleepcount'))$('sleepcount').textContent=`Morgon om ${Math.ceil(game.sleeping)} sekunder …`;persist();view.render()}
button('pause',()=>{if(game.mode==='play')game.mode='pause';else if(game.mode==='pause')play();paint()});button('interact',()=>{game.interact();paint()});button('jump',()=>game.jump());
$('attack').addEventListener('pointerdown',e=>{e.preventDefault();if(game.mode!=='play')return;attackId=e.pointerId;input.attack=true;e.currentTarget.setPointerCapture(e.pointerId)});
for(const event of ['pointerup','pointercancel','lostpointercapture'])$('attack').addEventListener(event,e=>{if(e.pointerId===attackId){input.attack=false;attackId=null}});
const stick=$('joystick');function moveJoy(e){const r=stick.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,dx=(e.clientX-cx)/42,dy=(e.clientY-cy)/42,len=Math.max(1,Math.hypot(dx,dy));joy={x:dx/len,y:dy/len};$('stick').style.transform=`translate(${joy.x*35}px,${joy.y*35}px)`}
stick.addEventListener('pointerdown',e=>{e.preventDefault();if(game.mode!=='play')return;joyId=e.pointerId;stick.setPointerCapture(e.pointerId);moveJoy(e)});stick.addEventListener('pointermove',e=>{if(e.pointerId===joyId)moveJoy(e)});for(const ev of['pointerup','pointercancel','lostpointercapture'])stick.addEventListener(ev,e=>{if(e.pointerId===joyId){joyId=null;joy={x:0,y:0};$('stick').style.transform=''}});
$('game').addEventListener('pointerdown',e=>{if(game.mode!=='play')return;look={id:e.pointerId,x:e.clientX,y:e.clientY};$('game').setPointerCapture(e.pointerId)});$('game').addEventListener('pointermove',e=>{if(look?.id!==e.pointerId||game.mode!=='play')return;game.player.yaw-=(e.clientX-look.x)*.005;game.player.pitch=Math.max(-1.15,Math.min(1.15,game.player.pitch-(e.clientY-look.y)*.004));look={id:e.pointerId,x:e.clientX,y:e.clientY}});for(const ev of['pointerup','pointercancel'])$('game').addEventListener(ev,()=>look=null);
addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();keys.add(e.code);if(e.repeat)return;if(e.code==='KeyE'||e.code==='Enter')game.interact();if(e.code==='ShiftLeft'||e.code==='ShiftRight')game.jump();if(e.code==='KeyF')fullscreen();if(e.code==='Escape'){game.mode=game.mode==='play'?'pause':game.mode==='pause'?'play':game.mode;paint()}});addEventListener('keyup',e=>keys.delete(e.code));addEventListener('blur',()=>{resetInputs();if(game.mode==='play')game.mode='pause';paint()});document.addEventListener('visibilitychange',()=>{if(document.hidden){resetInputs();if(game.mode==='play')game.mode='pause';persist(true)}});addEventListener('resize',()=>view.resize());
function update(dt){input.forward=-joy.y+(keys.has('KeyW')||keys.has('ArrowUp')?1:0)-(keys.has('KeyS')||keys.has('ArrowDown')?1:0);input.side=joy.x+(keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0);if(game.mode==='play')game.player.yaw+=((keys.has('ArrowLeft')?1:0)-(keys.has('ArrowRight')?1:0))*dt*1.8;game.update(dt,{...input,attack:input.attack||keys.has('Space')});}
window.render_game_to_text=()=>game.text();window.advanceTime=ms=>{manualUntil=performance.now()+100;for(let t=0;t<ms;t+=1000/60)update(Math.min(1/60,(ms-t)/1000));paint()};
// Test access is present only under the explicit local QA flag; never enabled by default.
if(new URLSearchParams(location.search).has('qa'))window.__game=game;
function loop(now){const dt=Math.min(.05,(now-lastTime)/1000);lastTime=now;if(now>manualUntil)update(dt);paint();requestAnimationFrame(loop)}
paint();requestAnimationFrame(loop);
