import assert from "node:assert/strict";
import { Simulation } from "../sim.js";
const s = new Simulation();
s.start();
const heard = (kind) => s.sounds.some((e) => e.kind === kind);
s.attack();
assert(heard("swing"), "a missed hammer swing makes a sound");
s.sounds = [];
const sofa = s.resources.find((r) => r.kind === "sofa");
for (let i = 0; i < 3; i++) s.harvest(sofa);
assert(heard("chop") && heard("break"), "harvesting and breaking furniture have distinct sounds");
Object.assign(s.player, { x: 0, z: 0, y: 0.72, gold: 20 });
s.buy("sword", true);
const guard = s.guards[0];
Object.assign(guard, { x: 0, y: 0.72, z: 0 });
s.sounds = [];
s.move(guard, 0.5, 0);
s.move(guard, -1, 0);
assert(heard("step"), "walking guards make footsteps");
s.sounds = [];
s.translateRaft(s.raft, 0.5, 0);
assert(!heard("step"), "drifting aboard a raft is not a footstep");
const shark = s.addShark(guard.x + 2, guard.z);
s.aiAttack(guard, shark);
assert(heard("swing") && heard("hit"), "guard swings and hits are audible");
s.sounds = [];
s.time = 95;
s.updateSharks(0.1);
assert(heard("bite") && heard("chop"), "shark biting a raft makes bite and wood sounds");
s.sounds = [];
s.sound("step", { x: 1000, z: 1000, zone: "sea" });
s.sound("step", { x: 0, z: 0, zone: "belly" });
assert.equal(s.sounds.length, 0, "faraway crews and other zones are silent");
for (let i = 0; i < 200; i++) s.sound("step");
assert.equal(s.sounds.length, 64, "unconsumed sound queue is bounded");
console.log("PASS swing, chop, break, guard footsteps/combat, shark bites, distance, zones and bounded queue");
