import assert from 'node:assert/strict';
import {Simulation} from '../sim.js';
const fresh=()=>{const s=new Simulation();s.start();return s;};
const destroy=s=>{for(const p of [...s.raft.parts])s.damagePart(s.raft,p,500);};
const s=fresh(),r=s.raft,id=r.id;
s.addPart(r,'wall',0,1.5);s.player.wood=5;s.build('boat',5,0);const boat=s.boats[0];
destroy(s);r.x=1500;r.z=1500;s.player.wood=2;
Object.assign(s.player,{x:0,z:5,y:0});
const before=JSON.stringify(r);
assert(s.canBuild('floor',0,1).ok);assert.equal(JSON.stringify(r),before,'preview has no side effects');
assert(!s.build('floor',0,40));assert.equal(s.player.wood,2);assert.equal(JSON.stringify(r),before);
assert(!s.build('floor',0,1,3));assert(!s.build('wall',0,1));
assert(s.build('floor',0,1));assert.equal(r.id,id);assert.equal(boat.home,id);
assert.deepEqual([r.x,r.z,r.parts[0].x,r.parts[0].z,r.parts[0].hp],[0,1,0,0,100]);assert.equal(s.player.wood,1);
assert(s.build('floor',3,1));assert.equal(s.player.wood,0);assert.equal(r.parts.length,2);
assert(!s.build('floor',-3,1));assert(!s.build('floor',0,1));
console.log('PASS destroy complete raft, preview and invalid placement, distant rebuild, one-wood cost, preserved identity and expansion');
destroy(s);const empty=JSON.stringify(r);assert(!s.build('floor',0,1));assert.equal(JSON.stringify(r),empty);
s.player.wood=1;assert(s.build('floor',0,1));
console.log('PASS no free replacement, rebuilding again after acquiring wood');
const land=fresh();destroy(land);land.player.wood=2;const island=land.islands[0];Object.assign(land.player,{x:island.x,z:island.z});assert(!land.build('floor',island.x,island.z));assert.equal(land.player.wood,2);assert.equal(land.raft.parts.length,0);
const partial=fresh();partial.player.wood=2;partial.raft.x=1500;partial.raft.z=1500;assert(!partial.build('floor',0,1));assert.equal(partial.raft.parts.length,1);
const zone=fresh();destroy(zone);zone.raft.zone='belly';zone.player.wood=1;assert(zone.build('floor',0,1));assert.equal(zone.raft.zone,'sea');
console.log('PASS water-only replacement, no relocating surviving raft, recovery after an empty raft remains in whale');
const botSim=fresh(),b=botSim.bots[0],br=botSim.rafts.find(r=>r.id===b.raftId);br.parts=[];br.x+=2000;b.wood=1;b.think=0;const old={x:b.x,z:b.z};botSim.resources=[];botSim.updateBots(.1);assert.equal(br.parts.length,1);assert.equal(b.wood,0);assert.deepEqual({x:br.x,z:br.z},old);assert.equal(botSim.bots.length,49);
console.log('PASS bot captain rebuilds near itself for one wood, 49 bots retained');
